//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsiErp.Localizations.Resources.PurchaseOrdersAwaitingApprovals.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PurchaseOrdersAwaitingApprovalsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PurchaseOrdersAwaitingApprovalsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsiErp.Localizations.Resources.PurchaseOrdersAwaitingApprovals.Page.PurchaseOrder" +
                            "sAwaitingApprovalsResource", typeof(PurchaseOrdersAwaitingApprovalsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylanan Adet:.
        /// </summary>
        public static string ApprovedQuantityLabel {
            get {
                return ResourceManager.GetString("ApprovedQuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedarikçi ile İrtibat.
        /// </summary>
        public static string ComboboxContactSupplier {
            get {
                return ResourceManager.GetString("ComboboxContactSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzeltme.
        /// </summary>
        public static string ComboboxCorrection {
            get {
                return ResourceManager.GetString("ComboboxCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string ComboboxRejection {
            get {
                return ResourceManager.GetString("ComboboxRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olduğu Gibi Kullanılacak.
        /// </summary>
        public static string ComboboxToBeUsedAs {
            get {
                return ResourceManager.GetString("ComboboxToBeUsedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol Adedi:.
        /// </summary>
        public static string ControlQuantityLabel {
            get {
                return ResourceManager.GetString("ControlQuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ KOD.
        /// </summary>
        public static string CurrentAccountCardCode {
            get {
                return ResourceManager.GetString("CurrentAccountCardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ ÜNVAN.
        /// </summary>
        public static string CurrentAccountCardName {
            get {
                return ResourceManager.GetString("CurrentAccountCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hesap Ünvanı:.
        /// </summary>
        public static string CurrentAccountCardNameLabel {
            get {
                return ResourceManager.GetString("CurrentAccountCardNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğinize emin misiniz ?.
        /// </summary>
        public static string DeleteConfirmationDescriptionBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string DeleteConfirmationTitleBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hareket gören kayıtlar silinemez..
        /// </summary>
        public static string DeleteControlManager {
            get {
                return ResourceManager.GetString("DeleteControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla silindi..
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama:.
        /// </summary>
        public static string Description_Label {
            get {
                return ResourceManager.GetString("Description_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay Bekleyen Satın Alma Siparişleri.
        /// </summary>
        public static string EditModalTitle {
            get {
                return ResourceManager.GetString("EditModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay Bekleniyor.
        /// </summary>
        public static string EnumAwaitingQualityControlApproval {
            get {
                return ResourceManager.GetString("EnumAwaitingQualityControlApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şartlı Onaylandı.
        /// </summary>
        public static string EnumPartialApproval {
            get {
                return ResourceManager.GetString("EnumPartialApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay Verildi.
        /// </summary>
        public static string EnumQualityControlApproved {
            get {
                return ResourceManager.GetString("EnumQualityControlApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Edildi.
        /// </summary>
        public static string EnumReject {
            get {
                return ResourceManager.GetString("EnumReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnayBekleyenSatinAlmaSiparisleri.
        /// </summary>
        public static string ExportFileName {
            get {
                return ResourceManager.GetString("ExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay Bekleyen Satın Alma Siparişleri.
        /// </summary>
        public static string ExportTitle {
            get {
                return ResourceManager.GetString("ExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT TOLERANS.
        /// </summary>
        public static string LineGridBottomTolerance {
            get {
                return ResourceManager.GetString("LineGridBottomTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KONTROL SIKLIĞI.
        /// </summary>
        public static string LineGridControlFrequency {
            get {
                return ResourceManager.GetString("LineGridControlFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KONTROL TÜRÜ.
        /// </summary>
        public static string LineGridControlTypesName {
            get {
                return ResourceManager.GetString("LineGridControlTypesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLMASI GEREKEN ÖLÇÜ.
        /// </summary>
        public static string LineGridIdealMeasure {
            get {
                return ResourceManager.GetString("LineGridIdealMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATIR NO.
        /// </summary>
        public static string LineGridLineNr {
            get {
                return ResourceManager.GetString("LineGridLineNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖLÇÜ DEĞERİ.
        /// </summary>
        public static string LineGridMeasureValue {
            get {
                return ResourceManager.GetString("LineGridMeasureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜST TOLERANS.
        /// </summary>
        public static string LineGridUpperTolerance {
            get {
                return ResourceManager.GetString("LineGridUpperTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay Bekleyen Satın Alma Sipariş Satırları.
        /// </summary>
        public static string LineModalTitle {
            get {
                return ResourceManager.GetString("LineModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Bekleyin...
        /// </summary>
        public static string LoadingCaption {
            get {
                return ResourceManager.GetString("LoadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar Yükleniyor...
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölçü Değeri:.
        /// </summary>
        public static string MeasureValueLineLabel {
            get {
                return ResourceManager.GetString("MeasureValueLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz kayıt {0} tarafından kullanılmaktadır..
        /// </summary>
        public static string MessagePopupInformationDescriptionBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        public static string MessagePopupInformationTitleBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknik Resmi Görüntüle.
        /// </summary>
        public static string PreviewButton {
            get {
                return ResourceManager.GetString("PreviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SİPARİŞ TARİHİ.
        /// </summary>
        public static string PurchaseOrderDate {
            get {
                return ResourceManager.GetString("PurchaseOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SİPARİŞ NO.
        /// </summary>
        public static string PurchaseOrderFicheNo {
            get {
                return ResourceManager.GetString("PurchaseOrderFicheNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Numarası:.
        /// </summary>
        public static string PurchaseOrderFicheNoLabel {
            get {
                return ResourceManager.GetString("PurchaseOrderFicheNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değer Ekle.
        /// </summary>
        public static string PurchaseOrdersAwaitingApprovalLinesContextChange {
            get {
                return ResourceManager.GetString("PurchaseOrdersAwaitingApprovalLinesContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string PurchaseOrdersAwaitingApprovalLinesContextRefresh {
            get {
                return ResourceManager.GetString("PurchaseOrdersAwaitingApprovalLinesContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Uygunsuzluk Kaydı Oluştur.
        /// </summary>
        public static string PurchaseOrdersAwaitingApprovalsContextPurchaseUnsuitability {
            get {
                return ResourceManager.GetString("PurchaseOrdersAwaitingApprovalsContextPurchaseUnsuitability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalite Onayı Ver.
        /// </summary>
        public static string PurchaseOrdersAwaitingApprovalsContextQualityApproval {
            get {
                return ResourceManager.GetString("PurchaseOrdersAwaitingApprovalsContextQualityApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalite Onayını İptal Et.
        /// </summary>
        public static string PurchaseOrdersAwaitingApprovalsContextQualityApprovalCancel {
            get {
                return ResourceManager.GetString("PurchaseOrdersAwaitingApprovalsContextQualityApprovalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string PurchaseOrdersAwaitingApprovalsContextRefresh {
            get {
                return ResourceManager.GetString("PurchaseOrdersAwaitingApprovalsContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İncele.
        /// </summary>
        public static string PurchaseOrdersAwaitingApprovalsContextReview {
            get {
                return ResourceManager.GetString("PurchaseOrdersAwaitingApprovalsContextReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURUM.
        /// </summary>
        public static string PurchaseOrdersAwaitingApprovalStateEnum {
            get {
                return ResourceManager.GetString("PurchaseOrdersAwaitingApprovalStateEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum:.
        /// </summary>
        public static string PurchaseOrdersAwaitingApprovalStateEnumLabel {
            get {
                return ResourceManager.GetString("PurchaseOrdersAwaitingApprovalStateEnumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygunsuzluk Aksiyonu:.
        /// </summary>
        public static string PurchaseUnsuitabilityActionLabel {
            get {
                return ResourceManager.GetString("PurchaseUnsuitabilityActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hesap Kodu:.
        /// </summary>
        public static string PurchaseUnsuitabilityCurrentAccountCardCodeLabel {
            get {
                return ResourceManager.GetString("PurchaseUnsuitabilityCurrentAccountCardCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hesap Ünvanı:.
        /// </summary>
        public static string PurchaseUnsuitabilityCurrentAccountCardNameLabel {
            get {
                return ResourceManager.GetString("PurchaseUnsuitabilityCurrentAccountCardNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih:.
        /// </summary>
        public static string PurchaseUnsuitabilityDate_Label {
            get {
                return ResourceManager.GetString("PurchaseUnsuitabilityDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama:.
        /// </summary>
        public static string PurchaseUnsuitabilityDescription_Label {
            get {
                return ResourceManager.GetString("PurchaseUnsuitabilityDescription_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygunsuzluk Fiş Numarası:.
        /// </summary>
        public static string PurchaseUnsuitabilityFicheNoLabel {
            get {
                return ResourceManager.GetString("PurchaseUnsuitabilityFicheNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Uygunsuzluk Kayıtları.
        /// </summary>
        public static string PurchaseUnsuitabilityModalTitle {
            get {
                return ResourceManager.GetString("PurchaseUnsuitabilityModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Numarası:.
        /// </summary>
        public static string PurchaseUnsuitabilityOrderFicheNoLabel {
            get {
                return ResourceManager.GetString("PurchaseUnsuitabilityOrderFicheNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parti Numarası:.
        /// </summary>
        public static string PurchaseUnsuitabilityPartyNoLabel {
            get {
                return ResourceManager.GetString("PurchaseUnsuitabilityPartyNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Kodu:.
        /// </summary>
        public static string PurchaseUnsuitabilityProductCodeLabel {
            get {
                return ResourceManager.GetString("PurchaseUnsuitabilityProductCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Açıklaması:.
        /// </summary>
        public static string PurchaseUnsuitabilityProductNameLabel {
            get {
                return ResourceManager.GetString("PurchaseUnsuitabilityProductNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygunsuzluk Başlığı:.
        /// </summary>
        public static string PurchaseUnsuitabilityUnsuitabilityNameLabel {
            get {
                return ResourceManager.GetString("PurchaseUnsuitabilityUnsuitabilityNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı Miktar:.
        /// </summary>
        public static string PurchaseUnsuitabilityUnsuitableAmountLabel {
            get {
                return ResourceManager.GetString("PurchaseUnsuitabilityUnsuitableAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalite Onay Tarihi:.
        /// </summary>
        public static string QualityApprovalDateLabel {
            get {
                return ResourceManager.GetString("QualityApprovalDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay Bekleyen Satın Alma Siparişleri.
        /// </summary>
        public static string UICurrentMenu {
            get {
                return ResourceManager.GetString("UICurrentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Böyle bir teknik resim bulunmamaktadır..
        /// </summary>
        public static string UIInformationFileMessage {
            get {
                return ResourceManager.GetString("UIInformationFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        public static string UIInformationFileTitle {
            get {
                return ResourceManager.GetString("UIInformationFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalite Kontrol &gt; Hareketler.
        /// </summary>
        public static string UIPreviousMenu {
            get {
                return ResourceManager.GetString("UIPreviousMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygunsuzluk kaydı oluştururken aksiyon ve uygunsuz miktar girişi zorunludur..
        /// </summary>
        public static string UIWarningAmountActionMessage {
            get {
                return ResourceManager.GetString("UIWarningAmountActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        public static string UIWarningAmountActionTitle {
            get {
                return ResourceManager.GetString("UIWarningAmountActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durumu &quot;Red&quot; olmayan kayıtlar için satın alma uygunsuzluk kaydı oluşturulamaz..
        /// </summary>
        public static string UIWarningPurchUnsMessage {
            get {
                return ResourceManager.GetString("UIWarningPurchUnsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        public static string UIWarningPurchUnsTitle {
            get {
                return ResourceManager.GetString("UIWarningPurchUnsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygunsuzluk Başlıkları.
        /// </summary>
        public static string UnsuitabilityItemsModalTitle {
            get {
                return ResourceManager.GetString("UnsuitabilityItemsModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAŞLIK KODU.
        /// </summary>
        public static string UnsutabilityItemModalGridCode {
            get {
                return ResourceManager.GetString("UnsutabilityItemModalGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAŞLIK ADI.
        /// </summary>
        public static string UnsutabilityItemModalGridName {
            get {
                return ResourceManager.GetString("UnsutabilityItemModalGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylayan:.
        /// </summary>
        public static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
    }
}
