//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsiErp.Localizations.Resources.ExchangeRates.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExchangeRatesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExchangeRatesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsiErp.Localizations.Resources.ExchangeRates.Page.ExchangeRatesResource", typeof(ExchangeRatesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALIŞ KURU.
        /// </summary>
        public static string BuyingRate {
            get {
                return ResourceManager.GetString("BuyingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alış Kuru:.
        /// </summary>
        public static string BuyingRateLabel {
            get {
                return ResourceManager.GetString("BuyingRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı kodlu bir kayıt bulunmaktadır..
        /// </summary>
        public static string CodeControlManager {
            get {
                return ResourceManager.GetString("CodeControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARA BİRİMİ KODU.
        /// </summary>
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Birimi Kodu:.
        /// </summary>
        public static string CurrencyCodeLabel {
            get {
                return ResourceManager.GetString("CurrencyCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARA BİRİMİ KODU.
        /// </summary>
        public static string CurrencyModalGridCode {
            get {
                return ResourceManager.GetString("CurrencyModalGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARA BİRİMİ AÇIKLAMASI.
        /// </summary>
        public static string CurrencyModalGridName {
            get {
                return ResourceManager.GetString("CurrencyModalGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Birimleri.
        /// </summary>
        public static string CurrencyModalTitle {
            get {
                return ResourceManager.GetString("CurrencyModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARİH.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih:.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğinize emin misiniz ?.
        /// </summary>
        public static string DeleteConfirmationDescriptionBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string DeleteConfirmationTitleBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla silindi..
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurlar.
        /// </summary>
        public static string EditModalTitle {
            get {
                return ResourceManager.GetString("EditModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFEKTİF ALIŞ KURU.
        /// </summary>
        public static string EffectiveBuyingRate {
            get {
                return ResourceManager.GetString("EffectiveBuyingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efektif Alış Kuru:.
        /// </summary>
        public static string EffectiveBuyingRateLabel {
            get {
                return ResourceManager.GetString("EffectiveBuyingRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFEKTİF SATIŞ KURU.
        /// </summary>
        public static string EffectiveSaleRate {
            get {
                return ResourceManager.GetString("EffectiveSaleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efektif Satış Kuru:.
        /// </summary>
        public static string EffectiveSaleRateLabel {
            get {
                return ResourceManager.GetString("EffectiveSaleRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string ExchangeRateContextAdd {
            get {
                return ResourceManager.GetString("ExchangeRateContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string ExchangeRateContextChange {
            get {
                return ResourceManager.GetString("ExchangeRateContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string ExchangeRateContextDelete {
            get {
                return ResourceManager.GetString("ExchangeRateContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string ExchangeRateContextRefresh {
            get {
                return ResourceManager.GetString("ExchangeRateContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Bekleyin...
        /// </summary>
        public static string LoadingCaption {
            get {
                return ResourceManager.GetString("LoadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar Yükleniyor...
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz kayıt {0} tarafından kullanılmaktadır..
        /// </summary>
        public static string MessagePopupInformationDescriptionBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        public static string MessagePopupInformationTitleBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATIŞ KURU.
        /// </summary>
        public static string SaleRate {
            get {
                return ResourceManager.GetString("SaleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Kuru:.
        /// </summary>
        public static string SaleRateLabel {
            get {
                return ResourceManager.GetString("SaleRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Kuru Tablosu.
        /// </summary>
        public static string UICurrentMenu {
            get {
                return ResourceManager.GetString("UICurrentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DovizKurlari.
        /// </summary>
        public static string UIExportFileName {
            get {
                return ResourceManager.GetString("UIExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Kurları.
        /// </summary>
        public static string UIExportTitle {
            get {
                return ResourceManager.GetString("UIExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Sistem Tanımlamaları.
        /// </summary>
        public static string UIPreviousMenu {
            get {
                return ResourceManager.GetString("UIPreviousMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı kodlu bir kayıt bulunmaktadır..
        /// </summary>
        public static string UpdateControlManager {
            get {
                return ResourceManager.GetString("UpdateControlManager", resourceCulture);
            }
        }
    }
}
