//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsiErp.Localizations.Resources.CashFlowPlans.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CashFlowPlansResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CashFlowPlansResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsiErp.Localizations.Resources.CashFlowPlans.Page.CashFlowPlansResource", typeof(CashFlowPlansResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar.
        /// </summary>
        public static string AmountPivot {
            get {
                return ResourceManager.GetString("AmountPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderilen Ödeme.
        /// </summary>
        public static string BalanceTypeExpenditure {
            get {
                return ResourceManager.GetString("BalanceTypeExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen Ödeme.
        /// </summary>
        public static string BalanceTypeIncome {
            get {
                return ResourceManager.GetString("BalanceTypeIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞUBE ADI.
        /// </summary>
        public static string BankAccountGridBankBranchName {
            get {
                return ResourceManager.GetString("BankAccountGridBankBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANKA HESAP KODU.
        /// </summary>
        public static string BankAccountGridCode {
            get {
                return ResourceManager.GetString("BankAccountGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANKA HESAP ADI.
        /// </summary>
        public static string BankAccountGridName {
            get {
                return ResourceManager.GetString("BankAccountGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIFT KOD.
        /// </summary>
        public static string BankAccountGridSWIFTCode {
            get {
                return ResourceManager.GetString("BankAccountGridSWIFTCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Hesapları.
        /// </summary>
        public static string BankAccountModalTitle {
            get {
                return ResourceManager.GetString("BankAccountModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string CashFlowPlanLinesContextAdd {
            get {
                return ResourceManager.GetString("CashFlowPlanLinesContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string CashFlowPlanLinesContextChange {
            get {
                return ResourceManager.GetString("CashFlowPlanLinesContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string CashFlowPlanLinesContextDelete {
            get {
                return ResourceManager.GetString("CashFlowPlanLinesContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Alış Ekle.
        /// </summary>
        public static string CashFlowPlanLinesContextExchangePurchaseAdd {
            get {
                return ResourceManager.GetString("CashFlowPlanLinesContextExchangePurchaseAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Satış Ekle.
        /// </summary>
        public static string CashFlowPlanLinesContextExchangeSalesAdd {
            get {
                return ResourceManager.GetString("CashFlowPlanLinesContextExchangeSalesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masraf Tutarı Ekle.
        /// </summary>
        public static string CashFlowPlanLinesContextExpenseAmountAdd {
            get {
                return ResourceManager.GetString("CashFlowPlanLinesContextExpenseAmountAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen Ödeme Ekle.
        /// </summary>
        public static string CashFlowPlanLinesContextIncomeAdd {
            get {
                return ResourceManager.GetString("CashFlowPlanLinesContextIncomeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılacak Ödeme Ekle.
        /// </summary>
        public static string CashFlowPlanLinesContextPaymentAdd {
            get {
                return ResourceManager.GetString("CashFlowPlanLinesContextPaymentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string CashFlowPlanLinesContextRefresh {
            get {
                return ResourceManager.GetString("CashFlowPlanLinesContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankalar Arası Virman Ekle.
        /// </summary>
        public static string CashFlowPlanLinesContextTransferAdd {
            get {
                return ResourceManager.GetString("CashFlowPlanLinesContextTransferAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string CashFlowPlansContextAdd {
            get {
                return ResourceManager.GetString("CashFlowPlansContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string CashFlowPlansContextChange {
            get {
                return ResourceManager.GetString("CashFlowPlansContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string CashFlowPlansContextDelete {
            get {
                return ResourceManager.GetString("CashFlowPlansContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string CashFlowPlansContextRefresh {
            get {
                return ResourceManager.GetString("CashFlowPlansContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAN KODU.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Kodu:.
        /// </summary>
        public static string CodeLabel {
            get {
                return ResourceManager.GetString("CodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ KOD.
        /// </summary>
        public static string CurrentAccountPopupGridCode {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ ÜNVAN.
        /// </summary>
        public static string CurrentAccountPopupGridName {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YETKİLİ.
        /// </summary>
        public static string CurrentAccountPopupGridResponsible {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TELEFON.
        /// </summary>
        public static string CurrentAccountPopupGridTel1 {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridTel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hesap Kartları.
        /// </summary>
        public static string CurrentAccountPopupTitle {
            get {
                return ResourceManager.GetString("CurrentAccountPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğinize emin misiniz ?.
        /// </summary>
        public static string DeleteConfirmationDescriptionBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string DeleteConfirmationTitleBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hareket gören kayıtlar silinemez..
        /// </summary>
        public static string DeleteControlManager {
            get {
                return ResourceManager.GetString("DeleteControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla silindi..
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama:.
        /// </summary>
        public static string Description_Label {
            get {
                return ResourceManager.GetString("Description_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar:.
        /// </summary>
        public static string DetailedCrudAmount_Label {
            get {
                return ResourceManager.GetString("DetailedCrudAmount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banka Hesap Adı:.
        /// </summary>
        public static string DetailedCrudBankAccountNameLabel {
            get {
                return ResourceManager.GetString("DetailedCrudBankAccountNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakiye Türü:.
        /// </summary>
        public static string DetailedCrudCashFlowPlansBalanceTypeLabel {
            get {
                return ResourceManager.GetString("DetailedCrudCashFlowPlansBalanceTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Türü:.
        /// </summary>
        public static string DetailedCrudCashFlowPlansTransactionTypeLabel {
            get {
                return ResourceManager.GetString("DetailedCrudCashFlowPlansTransactionTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Birimi:.
        /// </summary>
        public static string DetailedCrudCurrencyCodeLabel {
            get {
                return ResourceManager.GetString("DetailedCrudCurrencyCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Ünvan:.
        /// </summary>
        public static string DetailedCrudCurrentAccountNameLabel {
            get {
                return ResourceManager.GetString("DetailedCrudCurrentAccountNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih:.
        /// </summary>
        public static string DetailedCrudDate_Label {
            get {
                return ResourceManager.GetString("DetailedCrudDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masraf Tutar:.
        /// </summary>
        public static string DetailedCrudExpenseAmount_Label {
            get {
                return ResourceManager.GetString("DetailedCrudExpenseAmount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakit Akış Plan Detay İşlemleri.
        /// </summary>
        public static string DetailedCrudModalTitle {
            get {
                return ResourceManager.GetString("DetailedCrudModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Açıklaması:.
        /// </summary>
        public static string DetailedCrudTransactionDescriptionLabel {
            get {
                return ResourceManager.GetString("DetailedCrudTransactionDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakit Akış Plan Detayları.
        /// </summary>
        public static string DetailedModalTitle {
            get {
                return ResourceManager.GetString("DetailedModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakit Akış Planları.
        /// </summary>
        public static string EditModalTitle {
            get {
                return ResourceManager.GetString("EditModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİTİŞ TARİHİ.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi:.
        /// </summary>
        public static string EndDateLabel {
            get {
                return ResourceManager.GetString("EndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKTİF.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiflik:.
        /// </summary>
        public static string IsActiveLabel {
            get {
                return ResourceManager.GetString("IsActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUTAR.
        /// </summary>
        public static string LineGridAmount_ {
            get {
                return ResourceManager.GetString("LineGridAmount_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANKA HESABI.
        /// </summary>
        public static string LineGridBankAccountName {
            get {
                return ResourceManager.GetString("LineGridBankAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAKİYE TÜRÜ.
        /// </summary>
        public static string LineGridCashFlowPlansBalanceType {
            get {
                return ResourceManager.GetString("LineGridCashFlowPlansBalanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İŞLEM TÜRÜ.
        /// </summary>
        public static string LineGridCashFlowPlansTransactionType {
            get {
                return ResourceManager.GetString("LineGridCashFlowPlansTransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ ÜNVAN.
        /// </summary>
        public static string LineGridCurrentAccountName {
            get {
                return ResourceManager.GetString("LineGridCurrentAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARİH.
        /// </summary>
        public static string LineGridDate_ {
            get {
                return ResourceManager.GetString("LineGridDate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MASRAF TUTARI.
        /// </summary>
        public static string LineGridExpenseAmount_ {
            get {
                return ResourceManager.GetString("LineGridExpenseAmount_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALICI BANKA HESABI.
        /// </summary>
        public static string LineGridRecieverBankAccountName {
            get {
                return ResourceManager.GetString("LineGridRecieverBankAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÖNDERİCİ BANKA HESABI.
        /// </summary>
        public static string LineGridTransmitterBankAccountName {
            get {
                return ResourceManager.GetString("LineGridTransmitterBankAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Bekleyin...
        /// </summary>
        public static string LoadingCaption {
            get {
                return ResourceManager.GetString("LoadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar Yükleniyor...
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAŞLANGIÇ TARİHİ.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi:.
        /// </summary>
        public static string StartDateLabel {
            get {
                return ResourceManager.GetString("StartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Alış.
        /// </summary>
        public static string TransactionTypeExchangePurchase {
            get {
                return ResourceManager.GetString("TransactionTypeExchangePurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Satış.
        /// </summary>
        public static string TransactionTypeExchangeSales {
            get {
                return ResourceManager.GetString("TransactionTypeExchangeSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masraf Tutarı.
        /// </summary>
        public static string TransactionTypeExpenseAmount {
            get {
                return ResourceManager.GetString("TransactionTypeExpenseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen Ödeme.
        /// </summary>
        public static string TransactionTypeIncome {
            get {
                return ResourceManager.GetString("TransactionTypeIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılacak Ödeme.
        /// </summary>
        public static string TransactionTypePayment {
            get {
                return ResourceManager.GetString("TransactionTypePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankalar Arası Virman.
        /// </summary>
        public static string TransactionTypeTransferBetweenBanks {
            get {
                return ResourceManager.GetString("TransactionTypeTransferBetweenBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz satır kalıcı olarak silinecektir..
        /// </summary>
        public static string UIConfirmationPopupMessageLineBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupMessageLineBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string UIConfirmationPopupTitleBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakit Akış Planları.
        /// </summary>
        public static string UICurrentMenu {
            get {
                return ResourceManager.GetString("UICurrentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NakitAkisPlanlari.
        /// </summary>
        public static string UIExportFileName {
            get {
                return ResourceManager.GetString("UIExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nakit Akış Planları.
        /// </summary>
        public static string UIExportTitle {
            get {
                return ResourceManager.GetString("UIExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finans Yönetimi &gt; Hareketler.
        /// </summary>
        public static string UIPreviousMenu {
            get {
                return ResourceManager.GetString("UIPreviousMenu", resourceCulture);
            }
        }
    }
}
