//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsiErp.Localizations.Resources.ContractProductionTrackings.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContractProductionTrackingsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContractProductionTrackingsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsiErp.Localizations.Resources.ContractProductionTrackings.Page.ContractProductio" +
                            "nTrackingsResource", typeof(ContractProductionTrackingsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FASON TAKİP KODU.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı kodlu bir kayıt bulunmaktadır..
        /// </summary>
        public static string CodeControlManager {
            get {
                return ResourceManager.GetString("CodeControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fason Takip Kodu:.
        /// </summary>
        public static string CodeLabel {
            get {
                return ResourceManager.GetString("CodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string ContractProductionTrackingContextAdd {
            get {
                return ResourceManager.GetString("ContractProductionTrackingContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string ContractProductionTrackingContextChange {
            get {
                return ResourceManager.GetString("ContractProductionTrackingContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string ContractProductionTrackingContextDelete {
            get {
                return ResourceManager.GetString("ContractProductionTrackingContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string ContractProductionTrackingContextRefresh {
            get {
                return ResourceManager.GetString("ContractProductionTrackingContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ HESAP KODU.
        /// </summary>
        public static string CurrentAccountCardCode {
            get {
                return ResourceManager.GetString("CurrentAccountCardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hesap Kodu:.
        /// </summary>
        public static string CurrentAccountCardCodeLabel {
            get {
                return ResourceManager.GetString("CurrentAccountCardCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ KOD.
        /// </summary>
        public static string CurrentAccountPopupGridCode {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-POSTA.
        /// </summary>
        public static string CurrentAccountPopupGridEmail {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ ÜNVAN.
        /// </summary>
        public static string CurrentAccountPopupGridName {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLGİLİ.
        /// </summary>
        public static string CurrentAccountPopupGridResponsible {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERGİ NUMARASI.
        /// </summary>
        public static string CurrentAccountPopupGridTaxNumber {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridTaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TELEFON (1).
        /// </summary>
        public static string CurrentAccountPopupGridTel1 {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridTel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hesap Kartları.
        /// </summary>
        public static string CurrentAccountPopupTitle {
            get {
                return ResourceManager.GetString("CurrentAccountPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğinize emin misiniz ?.
        /// </summary>
        public static string DeleteConfirmationDescriptionBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string DeleteConfirmationTitleBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla silindi..
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fason Üretim Takip Kayıtları.
        /// </summary>
        public static string EditModalTitle {
            get {
                return ResourceManager.GetString("EditModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERATÖR.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör:.
        /// </summary>
        public static string EmployeeNameLabel {
            get {
                return ResourceManager.GetString("EmployeeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERATÖR KODU.
        /// </summary>
        public static string EmployeePopupGridCode {
            get {
                return ResourceManager.GetString("EmployeePopupGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERATÖR ADI.
        /// </summary>
        public static string EmployeePopupGridName {
            get {
                return ResourceManager.GetString("EmployeePopupGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatörler.
        /// </summary>
        public static string EmployeePopupTitle {
            get {
                return ResourceManager.GetString("EmployeePopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAMAMLANDI.
        /// </summary>
        public static string IsFinished {
            get {
                return ResourceManager.GetString("IsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamamlandı:.
        /// </summary>
        public static string IsFinishedLabel {
            get {
                return ResourceManager.GetString("IsFinishedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Bekleyin...
        /// </summary>
        public static string LoadingCaption {
            get {
                return ResourceManager.GetString("LoadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar Yükleniyor...
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz kayıt {0} tarafından kullanılmaktadır..
        /// </summary>
        public static string MessagePopupInformationDescriptionBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        public static string MessagePopupInformationTitleBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİTİŞ TARİHİ.
        /// </summary>
        public static string OperationEndDate {
            get {
                return ResourceManager.GetString("OperationEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi:.
        /// </summary>
        public static string OperationEndDateLabel {
            get {
                return ResourceManager.GetString("OperationEndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Saati:.
        /// </summary>
        public static string OperationEndTimeLabel {
            get {
                return ResourceManager.GetString("OperationEndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAŞLANGIÇ TARİHİ.
        /// </summary>
        public static string OperationStartDate {
            get {
                return ResourceManager.GetString("OperationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi:.
        /// </summary>
        public static string OperationStartDateLabel {
            get {
                return ResourceManager.GetString("OperationStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Saati:.
        /// </summary>
        public static string OperationStartTimeLabel {
            get {
                return ResourceManager.GetString("OperationStartTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERASYON SÜRESİ.
        /// </summary>
        public static string OperationTime {
            get {
                return ResourceManager.GetString("OperationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasyon Süresi:.
        /// </summary>
        public static string OperationTimeLabel {
            get {
                return ResourceManager.GetString("OperationTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLANLANAN MİKTAR.
        /// </summary>
        public static string PlannedQuantity {
            get {
                return ResourceManager.GetString("PlannedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRETİLEN MİKTAR.
        /// </summary>
        public static string ProducedQuantity {
            get {
                return ResourceManager.GetString("ProducedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretilen Miktar:.
        /// </summary>
        public static string ProducedQuantityLabel {
            get {
                return ResourceManager.GetString("ProducedQuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK KODU.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Kodu:.
        /// </summary>
        public static string ProductCodeLabel {
            get {
                return ResourceManager.GetString("ProductCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Açıklaması:.
        /// </summary>
        public static string ProductNameLabel {
            get {
                return ResourceManager.GetString("ProductNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK KODU.
        /// </summary>
        public static string ProductPopupGridCode {
            get {
                return ResourceManager.GetString("ProductPopupGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK AÇIKLAMASI.
        /// </summary>
        public static string ProductPopupGridName {
            get {
                return ResourceManager.GetString("ProductPopupGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Kartları.
        /// </summary>
        public static string ProductPopupTitle {
            get {
                return ResourceManager.GetString("ProductPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARDİYA KODU.
        /// </summary>
        public static string ShiftCode {
            get {
                return ResourceManager.GetString("ShiftCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vardiya:.
        /// </summary>
        public static string ShiftCodeLabel {
            get {
                return ResourceManager.GetString("ShiftCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARDİYA KODU.
        /// </summary>
        public static string ShiftPopupGridCode {
            get {
                return ResourceManager.GetString("ShiftPopupGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARDİYA ADI.
        /// </summary>
        public static string ShiftPopupGridName {
            get {
                return ResourceManager.GetString("ShiftPopupGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vardiyalar.
        /// </summary>
        public static string ShiftPopupTitle {
            get {
                return ResourceManager.GetString("ShiftPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTASYON KODU.
        /// </summary>
        public static string StationCode {
            get {
                return ResourceManager.GetString("StationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyon:.
        /// </summary>
        public static string StationCodeLabel {
            get {
                return ResourceManager.GetString("StationCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTASYON KODU.
        /// </summary>
        public static string StationPopupGridCode {
            get {
                return ResourceManager.GetString("StationPopupGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTASYON AÇIKLAMASI.
        /// </summary>
        public static string StationPopupGridName {
            get {
                return ResourceManager.GetString("StationPopupGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş İstasyonları.
        /// </summary>
        public static string StationPopupTitle {
            get {
                return ResourceManager.GetString("StationPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen önce başlangıç tarihini seçiniz..
        /// </summary>
        public static string UIConfirmationPopupDateBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupDateBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz kayıt kalıcı olarak silinecektir..
        /// </summary>
        public static string UIConfirmationPopupMessageBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupMessageBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikkat.
        /// </summary>
        public static string UIConfirmationPopupTitleBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fason İmalat Takip Kayıtları.
        /// </summary>
        public static string UICurrentMenu {
            get {
                return ResourceManager.GetString("UICurrentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FasonImalat.
        /// </summary>
        public static string UIExportFileName {
            get {
                return ResourceManager.GetString("UIExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fason İmalat Takip Kayıtları.
        /// </summary>
        public static string UIExportTitle {
            get {
                return ResourceManager.GetString("UIExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Yönetimi &gt; Üretim Takip Kayıtları.
        /// </summary>
        public static string UIPreviousMenu {
            get {
                return ResourceManager.GetString("UIPreviousMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı kodlu bir kayıt bulunmaktadır..
        /// </summary>
        public static string UpdateControlManager {
            get {
                return ResourceManager.GetString("UpdateControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen cari hesap kartı seçin..
        /// </summary>
        public static string ValidatorCurrentAccountID {
            get {
                return ResourceManager.GetString("ValidatorCurrentAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen çalışan seçin..
        /// </summary>
        public static string ValidatorEmployeeID {
            get {
                return ResourceManager.GetString("ValidatorEmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen vardiya seçin..
        /// </summary>
        public static string ValidatorShiftID {
            get {
                return ResourceManager.GetString("ValidatorShiftID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen iş istasyonu seçin..
        /// </summary>
        public static string ValidatorStationID {
            get {
                return ResourceManager.GetString("ValidatorStationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Emri Kodu:.
        /// </summary>
        public static string WordOrderCodeLabel {
            get {
                return ResourceManager.GetString("WordOrderCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İŞ EMRİ NO.
        /// </summary>
        public static string WorkOrderCode {
            get {
                return ResourceManager.GetString("WorkOrderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İŞ EMRİ KODU.
        /// </summary>
        public static string WorkOrderPopupGridCode {
            get {
                return ResourceManager.GetString("WorkOrderPopupGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK KODU.
        /// </summary>
        public static string WorkOrderPopupGridProductCode {
            get {
                return ResourceManager.GetString("WorkOrderPopupGridProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK AÇIKLAMASI.
        /// </summary>
        public static string WorkOrderPopupGridProductName {
            get {
                return ResourceManager.GetString("WorkOrderPopupGridProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İŞ EMRİ NO.
        /// </summary>
        public static string WorkOrderPopupGridWorkOrderNo {
            get {
                return ResourceManager.GetString("WorkOrderPopupGridWorkOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Emirleri.
        /// </summary>
        public static string WorkOrderPopupTitle {
            get {
                return ResourceManager.GetString("WorkOrderPopupTitle", resourceCulture);
            }
        }
    }
}
