using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TsiErp.Entities.TableConstant
{
    public static class Tables
    {
        public static readonly string BillsofMaterialLines = "BillsofMaterialLines";
        public static readonly string BillsofMaterials = "BillsofMaterials";
        public static readonly string Branches = "Branches";
        public static readonly string ByDateStockMovements = "ByDateStockMovements";
        public static readonly string CalendarDays = "CalendarDays";
        public static readonly string CalendarLines = "CalendarLines";
        public static readonly string Calendars = "Calendars";
        public static readonly string CalibrationRecords = "CalibrationRecords";
        public static readonly string CalibrationVerifications = "CalibrationVerifications";
        public static readonly string ContractProductionTrackings = "ContractProductionTrackings";
        public static readonly string ContractUnsuitabilityItems = "ContractUnsuitabilityItems";
        public static readonly string Currencies = "Currencies";
        public static readonly string CurrentAccountCards = "CurrentAccountCards";
        public static readonly string CustomerComplaintItems = "CustomerComplaintItems";
        public static readonly string Departments = "Departments";
        public static readonly string Employees = "Employees";
        public static readonly string EquipmentRecords = "EquipmentRecords";
        public static readonly string ExchangeRates = "ExchangeRates";
        public static readonly string FinalControlUnsuitabilityItems = "FinalControlUnsuitabilityItems";
        public static readonly string FinalControlUnsuitabilityReports = "FinalControlUnsuitabilityReports";
        public static readonly string ForecastLines = "ForecastLines";
        public static readonly string Forecasts = "Forecasts";
        public static readonly string GrandTotalStockMovements = "GrandTotalStockMovements";
        public static readonly string HaltReasons = "HaltReasons";
        public static readonly string Logs = "Logs";
        public static readonly string MaintenanceInstructionLines = "MaintenanceInstructionLines";
        public static readonly string MaintenanceInstructions = "MaintenanceInstructions";
        public static readonly string MaintenancePeriods = "MaintenancePeriods";
        public static readonly string Menus = "Menus";
        public static readonly string OperationUnsuitabilityItems = "OperationUnsuitabilityItems";
        public static readonly string OperationUnsuitabilityReports = "OperationUnsuitabilityReports";
        public static readonly string PaymentPlans = "PaymentPlans";
        public static readonly string Periods = "Periods";
        public static readonly string PlannedMaintenanceLines = "PlannedMaintenanceLines";
        public static readonly string PlannedMaintenances = "PlannedMaintenances";
        public static readonly string ProductGroups = "ProductGroups";
        public static readonly string ProductionOrderChangeItems = "ProductionOrderChangeItems";
        public static readonly string ProductionOrders = "ProductionOrders";
        public static readonly string ProductionTrackingHaltLines = "ProductionTrackingHaltLines";
        public static readonly string ProductionTrackings = "ProductionTrackings";
        public static readonly string ProductReferanceNumbers = "ProductReferanceNumbers";
        public static readonly string Products = "Products";
        public static readonly string ProductsOperationLines = "ProductsOperationLines";
        public static readonly string ProductsOperations = "ProductsOperations";
        public static readonly string PurchaseOrderLines = "PurchaseOrderLines";
        public static readonly string PurchaseOrders = "PurchaseOrders";
        public static readonly string PurchasePriceLines = "PurchasePriceLines";
        public static readonly string PurchasePrices = "PurchasePrices";
        public static readonly string PurchaseRequestLines = "PurchaseRequestLines";
        public static readonly string PurchaseRequests = "PurchaseRequests";
        public static readonly string PurchaseUnsuitabilityReports = "PurchaseUnsuitabilityReports";
        public static readonly string PurchasingUnsuitabilityItems = "PurchasingUnsuitabilityItems";
        public static readonly string RouteLines = "RouteLines";
        public static readonly string Routes = "Routes";
        public static readonly string SalesOrderLines = "SalesOrderLines";
        public static readonly string SalesOrders = "SalesOrders";
        public static readonly string SalesPriceLines = "SalesPriceLines";
        public static readonly string SalesPrices = "SalesPrices";
        public static readonly string SalesPropositionLines = "SalesPropositionLines";
        public static readonly string SalesPropositions = "SalesPropositions";
        public static readonly string ShiftLines = "ShiftLines";
        public static readonly string Shifts = "Shifts";
        public static readonly string ShippingAdresses = "ShippingAdresses";
        public static readonly string StationGroups = "StationGroups";
        public static readonly string StationInventories = "StationInventories";
        public static readonly string Stations = "Stations";
        public static readonly string TechnicalDrawings = "TechnicalDrawings";
        public static readonly string TemplateOperationLines = "TemplateOperationLines";
        public static readonly string TemplateOperations = "TemplateOperations";
        public static readonly string UnitSets = "UnitSets";
        public static readonly string UnplannedMaintenanceLines = "UnplannedMaintenanceLines";
        public static readonly string UnplannedMaintenances = "UnplannedMaintenances";
        public static readonly string UserGroups = "UserGroups";
        public static readonly string Users = "Users";
        public static readonly string VsmSchemas = "VsmSchemas";
        public static readonly string Warehouses = "Warehouses";
        public static readonly string WorkOrders = "WorkOrders";
        public static readonly string StockFiches = "StockFiches";
        public static readonly string StockFicheLines = "StockFicheLines";
        public static readonly string ProgVersions = "ProgVersions";
        public static readonly string UnsuitabilityTypesItems = "UnsuitabilityTypesItems";
        public static readonly string UnsuitabilityItems = "UnsuitabilityItems";
    }
}
