//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsiErp.Localizations.Resources.Forecasts.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ForecastsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ForecastsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsiErp.Localizations.Resources.Forecasts.Page.ForecastsResource", typeof(ForecastsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar:.
        /// </summary>
        public static string AmountLineLabel {
            get {
                return ResourceManager.GetString("AmountLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞUBE KODU.
        /// </summary>
        public static string BranchesPopupGridCode {
            get {
                return ResourceManager.GetString("BranchesPopupGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞUBE ADI.
        /// </summary>
        public static string BranchesPopupGridName {
            get {
                return ResourceManager.GetString("BranchesPopupGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şubeler.
        /// </summary>
        public static string BranchModalTitle {
            get {
                return ResourceManager.GetString("BranchModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞUBE ADI.
        /// </summary>
        public static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube Kodu:.
        /// </summary>
        public static string BranchNameLabel {
            get {
                return ResourceManager.GetString("BranchNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞUBE KODU.
        /// </summary>
        public static string BranchPopupGridCode {
            get {
                return ResourceManager.GetString("BranchPopupGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞUBE ADI.
        /// </summary>
        public static string BranchPopupGridName {
            get {
                return ResourceManager.GetString("BranchPopupGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şubeler.
        /// </summary>
        public static string BranchPopupTitle {
            get {
                return ResourceManager.GetString("BranchPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORECAST KODU.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı numaralı bir kayıt bulunmaktadır..
        /// </summary>
        public static string CodeControlManager {
            get {
                return ResourceManager.GetString("CodeControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Kodu:.
        /// </summary>
        public static string CodeLabel {
            get {
                return ResourceManager.GetString("CodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hesap Kodu:.
        /// </summary>
        public static string CurrentAccountCardCodeLabel {
            get {
                return ResourceManager.GetString("CurrentAccountCardCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ ÜNVAN.
        /// </summary>
        public static string CurrentAccountCardName {
            get {
                return ResourceManager.GetString("CurrentAccountCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hesap Ünvanı:.
        /// </summary>
        public static string CurrentAccountCardNameLabel {
            get {
                return ResourceManager.GetString("CurrentAccountCardNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ KOD.
        /// </summary>
        public static string CurrentAccountPopupGridCode {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-POSTA.
        /// </summary>
        public static string CurrentAccountPopupGridEmail {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ ÜNVAN.
        /// </summary>
        public static string CurrentAccountPopupGridName {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLGİLİ.
        /// </summary>
        public static string CurrentAccountPopupGridResponsible {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERGİ NUMARASI.
        /// </summary>
        public static string CurrentAccountPopupGridTaxNumber {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridTaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TELEFON (1).
        /// </summary>
        public static string CurrentAccountPopupGridTel1 {
            get {
                return ResourceManager.GetString("CurrentAccountPopupGridTel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hesap Kartları.
        /// </summary>
        public static string CurrentAccountPopupTitle {
            get {
                return ResourceManager.GetString("CurrentAccountPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Stok Kodu:.
        /// </summary>
        public static string CustomerProductCodeLineLabel {
            get {
                return ResourceManager.GetString("CustomerProductCodeLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğinize emin misiniz ?.
        /// </summary>
        public static string DeleteConfirmationDescriptionBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string DeleteConfirmationTitleBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla silindi..
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AÇIKLAMA.
        /// </summary>
        public static string Description_ {
            get {
                return ResourceManager.GetString("Description_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama:.
        /// </summary>
        public static string Description_Label {
            get {
                return ResourceManager.GetString("Description_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Forecast Kayıtları Satırları.
        /// </summary>
        public static string EditLineModalTitle {
            get {
                return ResourceManager.GetString("EditLineModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Forecast Kayıtları.
        /// </summary>
        public static string EditModalTitle {
            get {
                return ResourceManager.GetString("EditModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string ForecastContextAdd {
            get {
                return ResourceManager.GetString("ForecastContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string ForecastContextChange {
            get {
                return ResourceManager.GetString("ForecastContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string ForecastContextDelete {
            get {
                return ResourceManager.GetString("ForecastContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malzeme İhtiyaç Listesi.
        /// </summary>
        public static string ForecastContextMRP {
            get {
                return ResourceManager.GetString("ForecastContextMRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string ForecastContextRefresh {
            get {
                return ResourceManager.GetString("ForecastContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string ForecastLineContextAdd {
            get {
                return ResourceManager.GetString("ForecastLineContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string ForecastLineContextChange {
            get {
                return ResourceManager.GetString("ForecastLineContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string ForecastLineContextDelete {
            get {
                return ResourceManager.GetString("ForecastLineContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string ForecastLineContextRefresh {
            get {
                return ResourceManager.GetString("ForecastLineContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Kayıtları.
        /// </summary>
        public static string ForecastsChildMenu {
            get {
                return ResourceManager.GetString("ForecastsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi:.
        /// </summary>
        public static string LineEndDateLabel {
            get {
                return ResourceManager.GetString("LineEndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MİKTAR.
        /// </summary>
        public static string LineGridAmount {
            get {
                return ResourceManager.GetString("LineGridAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÜŞTERİ STOK KODU.
        /// </summary>
        public static string LineGridCustomerProductCode {
            get {
                return ResourceManager.GetString("LineGridCustomerProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİTİŞ TARİHİ.
        /// </summary>
        public static string LineGridEndDate {
            get {
                return ResourceManager.GetString("LineGridEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK KODU.
        /// </summary>
        public static string LineGridProductCode {
            get {
                return ResourceManager.GetString("LineGridProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK AÇIKLAMASI.
        /// </summary>
        public static string LineGridProductName {
            get {
                return ResourceManager.GetString("LineGridProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAŞLANGIÇ TARİHİ.
        /// </summary>
        public static string LineGridStartDate {
            get {
                return ResourceManager.GetString("LineGridStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Satırları.
        /// </summary>
        public static string LinePopupTitle {
            get {
                return ResourceManager.GetString("LinePopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi:.
        /// </summary>
        public static string LineStartDateLabel {
            get {
                return ResourceManager.GetString("LineStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Bekleyin...
        /// </summary>
        public static string LoadingCaption {
            get {
                return ResourceManager.GetString("LoadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar Yükleniyor...
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz kayıt {0} tarafından kullanılmaktadır..
        /// </summary>
        public static string MessagePopupInformationDescriptionBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        public static string MessagePopupInformationTitleBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube Kodu:.
        /// </summary>
        public static string MRPBranchCodeButtonEditLabel {
            get {
                return ResourceManager.GetString("MRPBranchCodeButtonEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRP Kodu:.
        /// </summary>
        public static string MRPCodeLabel {
            get {
                return ResourceManager.GetString("MRPCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih:.
        /// </summary>
        public static string MRPDate_Label {
            get {
                return ResourceManager.GetString("MRPDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama:.
        /// </summary>
        public static string MRPDescription_Label {
            get {
                return ResourceManager.GetString("MRPDescription_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi:.
        /// </summary>
        public static string MRPFilterEndDateLabel {
            get {
                return ResourceManager.GetString("MRPFilterEndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih Aralığı.
        /// </summary>
        public static string MRPFilterModalTitle {
            get {
                return ResourceManager.GetString("MRPFilterModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi:.
        /// </summary>
        public static string MRPFilterStartDateLabel {
            get {
                return ResourceManager.GetString("MRPFilterStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakım Malzeme İhtiyaç Planlaması:.
        /// </summary>
        public static string MRPIsMaintenanceMRPLabel {
            get {
                return ResourceManager.GetString("MRPIsMaintenanceMRPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube Kodu:.
        /// </summary>
        public static string MRPLineBranchCodeButtonEditLabel {
            get {
                return ResourceManager.GetString("MRPLineBranchCodeButtonEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string MRPLineContextChange {
            get {
                return ResourceManager.GetString("MRPLineContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string MRPLineContextDelete {
            get {
                return ResourceManager.GetString("MRPLineContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Satırlarını Sil.
        /// </summary>
        public static string MRPLineContextDeleteOrderLines {
            get {
                return ResourceManager.GetString("MRPLineContextDeleteOrderLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesaplamadan Kaldır.
        /// </summary>
        public static string MRPLineContextDoNotCalculate {
            get {
                return ResourceManager.GetString("MRPLineContextDoNotCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string MRPLineContextRefresh {
            get {
                return ResourceManager.GetString("MRPLineContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoktan Kullan.
        /// </summary>
        public static string MRPLineContextStockUsage {
            get {
                return ResourceManager.GetString("MRPLineContextStockUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedarikçi Seç.
        /// </summary>
        public static string MRPLineContextSupplier {
            get {
                return ResourceManager.GetString("MRPLineContextSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLANLANAN İHTİYAÇ MİKTARI.
        /// </summary>
        public static string MRPLineGridAmount {
            get {
                return ResourceManager.GetString("MRPLineGridAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK TOPLAMI.
        /// </summary>
        public static string MRPLineGridAmountOfStock {
            get {
                return ResourceManager.GetString("MRPLineGridAmountOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞUBE.
        /// </summary>
        public static string MRPLineGridBranchCode {
            get {
                return ResourceManager.GetString("MRPLineGridBranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK KODU.
        /// </summary>
        public static string MRPLineGridProductCode {
            get {
                return ResourceManager.GetString("MRPLineGridProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATIN ALMA İHTİYAÇ MİKTARI.
        /// </summary>
        public static string MRPLineGridRequirementAmount {
            get {
                return ResourceManager.GetString("MRPLineGridRequirementAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REZERVE MİKTARI.
        /// </summary>
        public static string MRPLineGridReservedAmount {
            get {
                return ResourceManager.GetString("MRPLineGridReservedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SİPARİŞ FİŞ NO.
        /// </summary>
        public static string MRPLineGridSalesOrderFicheNo {
            get {
                return ResourceManager.GetString("MRPLineGridSalesOrderFicheNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HESAPLANACAK.
        /// </summary>
        public static string MRPLineGridSalesOrderisCalculated {
            get {
                return ResourceManager.GetString("MRPLineGridSalesOrderisCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATIN ALMAYA DÖNÜŞTÜ.
        /// </summary>
        public static string MRPLineGridSalesOrderisPurchase {
            get {
                return ResourceManager.GetString("MRPLineGridSalesOrderisPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOKTAN KULLANILACAK.
        /// </summary>
        public static string MRPLineGridSalesOrderisStockUsage {
            get {
                return ResourceManager.GetString("MRPLineGridSalesOrderisStockUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMİN TARİHİ.
        /// </summary>
        public static string MRPLineGridSupplyDate {
            get {
                return ResourceManager.GetString("MRPLineGridSupplyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİRİM SETİ.
        /// </summary>
        public static string MRPLineGridUnitSetCode {
            get {
                return ResourceManager.GetString("MRPLineGridUnitSetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPO.
        /// </summary>
        public static string MRPLineGridWarehouseCode {
            get {
                return ResourceManager.GetString("MRPLineGridWarehouseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malzeme İhtiyaç Planlaması (MRP) Satırları.
        /// </summary>
        public static string MRPLineModalTitle {
            get {
                return ResourceManager.GetString("MRPLineModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depo Kodu:.
        /// </summary>
        public static string MRPLineWarehouseCodeButtonEditLabel {
            get {
                return ResourceManager.GetString("MRPLineWarehouseCodeButtonEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malzeme İhtiyaç Planlaması (MRP).
        /// </summary>
        public static string MRPModalTitle {
            get {
                return ResourceManager.GetString("MRPModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SİPARİŞ NO.
        /// </summary>
        public static string MRPOrderGridFicheNo {
            get {
                return ResourceManager.GetString("MRPOrderGridFicheNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referans Tarihi:.
        /// </summary>
        public static string MRPReferanceDateLabel {
            get {
                return ResourceManager.GetString("MRPReferanceDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum:.
        /// </summary>
        public static string MRPState_Label {
            get {
                return ResourceManager.GetString("MRPState_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depo Kodu:.
        /// </summary>
        public static string MRPWarehouseCodeButtonEditLabel {
            get {
                return ResourceManager.GetString("MRPWarehouseCodeButtonEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÖNEM KODU.
        /// </summary>
        public static string PeriodCode {
            get {
                return ResourceManager.GetString("PeriodCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dönem Kodu:.
        /// </summary>
        public static string PeriodNameLabel {
            get {
                return ResourceManager.GetString("PeriodNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÖNEM KODU.
        /// </summary>
        public static string PeriodPopupGridCode {
            get {
                return ResourceManager.GetString("PeriodPopupGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DÖNEM ADI.
        /// </summary>
        public static string PeriodPopupGridName {
            get {
                return ResourceManager.GetString("PeriodPopupGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dönemler.
        /// </summary>
        public static string PeriodPopupTitle {
            get {
                return ResourceManager.GetString("PeriodPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string ProcessAdd {
            get {
                return ResourceManager.GetString("ProcessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string ProcessDelete {
            get {
                return ResourceManager.GetString("ProcessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string ProcessRefresh {
            get {
                return ResourceManager.GetString("ProcessRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Kodu:.
        /// </summary>
        public static string ProductCodeLineLabel {
            get {
                return ResourceManager.GetString("ProductCodeLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Açıklaması:.
        /// </summary>
        public static string ProductNameLineLabel {
            get {
                return ResourceManager.GetString("ProductNameLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK KODU.
        /// </summary>
        public static string ProductPopupGridCode {
            get {
                return ResourceManager.GetString("ProductPopupGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK AÇIKLAMASI.
        /// </summary>
        public static string ProductPopupGridName {
            get {
                return ResourceManager.GetString("ProductPopupGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Kartları.
        /// </summary>
        public static string ProductPopupTitle {
            get {
                return ResourceManager.GetString("ProductPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tedarikçiler.
        /// </summary>
        public static string SupplierModalTitle {
            get {
                return ResourceManager.GetString("SupplierModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEDARİKÇİ.
        /// </summary>
        public static string SupplierPopupGridCurrentAccountName {
            get {
                return ResourceManager.GetString("SupplierPopupGridCurrentAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARA BİRİMİ.
        /// </summary>
        public static string SupplierPopupGridCurrenyCode {
            get {
                return ResourceManager.GetString("SupplierPopupGridCurrenyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK KODU.
        /// </summary>
        public static string SupplierPopupGridProductCode {
            get {
                return ResourceManager.GetString("SupplierPopupGridProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMİN TARİH GÜNÜ.
        /// </summary>
        public static string SupplierPopupGridSupplyDate {
            get {
                return ResourceManager.GetString("SupplierPopupGridSupplyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİRİM FİYAT.
        /// </summary>
        public static string SupplierPopupGridUnitPrice {
            get {
                return ResourceManager.GetString("SupplierPopupGridUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOPLAM ADET.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Adet:.
        /// </summary>
        public static string TotalLabel {
            get {
                return ResourceManager.GetString("TotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz satır kalıcı olarak silinecektir..
        /// </summary>
        public static string UIConfirmationPopupLineMessage {
            get {
                return ResourceManager.GetString("UIConfirmationPopupLineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz forecast kalıcı olarak silinecektir..
        /// </summary>
        public static string UIConfirmationPopupMessageBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupMessageBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikkat.
        /// </summary>
        public static string UIConfirmationPopupTitleBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari hesap kartı seçilmeden satır ekleme işlemi yapılamaz..
        /// </summary>
        public static string UICurrentAccountMessage {
            get {
                return ResourceManager.GetString("UICurrentAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        public static string UICurrentAccountTitle {
            get {
                return ResourceManager.GetString("UICurrentAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Forecast Kayıtları.
        /// </summary>
        public static string UICurrentMenu {
            get {
                return ResourceManager.GetString("UICurrentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForecastKayitlari.
        /// </summary>
        public static string UIExportFileName {
            get {
                return ResourceManager.GetString("UIExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast Kayıtları.
        /// </summary>
        public static string UIExportTitle {
            get {
                return ResourceManager.GetString("UIExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Yönetimi &gt; Hareketler.
        /// </summary>
        public static string UIPreviousMenu {
            get {
                return ResourceManager.GetString("UIPreviousMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok kodu, Stok adı, Miktar, Başlangıç tarihi ve Bitiş tarihini eksiksiz doldurmadan  satır kaydetme işlemi yapılamamaktadır..
        /// </summary>
        public static string UIWarningPopupMessageBase {
            get {
                return ResourceManager.GetString("UIWarningPopupMessageBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        public static string UIWarningPopupTitleBase {
            get {
                return ResourceManager.GetString("UIWarningPopupTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı numaralı bir kayıt bulunmaktadır..
        /// </summary>
        public static string UpdateControlManager {
            get {
                return ResourceManager.GetString("UpdateControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen şube seçin..
        /// </summary>
        public static string ValidatorBranchID {
            get {
                return ResourceManager.GetString("ValidatorBranchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen kodu yazın..
        /// </summary>
        public static string ValidatorCodeEmpty {
            get {
                return ResourceManager.GetString("ValidatorCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod, 17 karakterden fazla olamaz..
        /// </summary>
        public static string ValidatorCodeMaxLenght {
            get {
                return ResourceManager.GetString("ValidatorCodeMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen cari hesap kartı seçin..
        /// </summary>
        public static string ValidatorCurrentAccountCardID {
            get {
                return ResourceManager.GetString("ValidatorCurrentAccountCardID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen dönem seçin..
        /// </summary>
        public static string ValidatorPeriodID {
            get {
                return ResourceManager.GetString("ValidatorPeriodID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEÇERLİLİK BİTİŞ TARİHİ.
        /// </summary>
        public static string ValidityEndDate {
            get {
                return ResourceManager.GetString("ValidityEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerlilik Bitiş Tarihi:.
        /// </summary>
        public static string ValidityEndDateLabel {
            get {
                return ResourceManager.GetString("ValidityEndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEÇERLİLİK BAŞLANGIÇ TARİHİ.
        /// </summary>
        public static string ValidityStartDate {
            get {
                return ResourceManager.GetString("ValidityStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerlilik Başlangıç Tarihi:.
        /// </summary>
        public static string ValidityStartDateLabel {
            get {
                return ResourceManager.GetString("ValidityStartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depo Kartları.
        /// </summary>
        public static string WarehouseModalTitle {
            get {
                return ResourceManager.GetString("WarehouseModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPO KODU.
        /// </summary>
        public static string WarehousesPopupGridCode {
            get {
                return ResourceManager.GetString("WarehousesPopupGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPO ADI.
        /// </summary>
        public static string WarehousesPopupGridName {
            get {
                return ResourceManager.GetString("WarehousesPopupGridName", resourceCulture);
            }
        }
    }
}
