//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsiErp.Localizations.Resources.PurchaseRequests.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PurchaseRequestsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PurchaseRequestsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsiErp.Localizations.Resources.PurchaseRequests.Page.PurchaseRequestsResource", typeof(PurchaseRequestsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞUBE KODU.
        /// </summary>
        public static string BranchCode {
            get {
                return ResourceManager.GetString("BranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞUBE KODU.
        /// </summary>
        public static string BranchModalGridCode {
            get {
                return ResourceManager.GetString("BranchModalGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AÇIKLAMA.
        /// </summary>
        public static string BranchModalGridDescription {
            get {
                return ResourceManager.GetString("BranchModalGridDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞUBE ADI.
        /// </summary>
        public static string BranchModalGridName {
            get {
                return ResourceManager.GetString("BranchModalGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şubeler.
        /// </summary>
        public static string BranchModalTitle {
            get {
                return ResourceManager.GetString("BranchModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube:.
        /// </summary>
        public static string BranchNameLabel {
            get {
                return ResourceManager.GetString("BranchNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı numaralı bir kayıt bulunmaktadır..
        /// </summary>
        public static string CodeControlManager {
            get {
                return ResourceManager.GetString("CodeControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylandı.
        /// </summary>
        public static string ConvertContextApprove {
            get {
                return ResourceManager.GetString("ConvertContextApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklemede.
        /// </summary>
        public static string ConvertContextPending {
            get {
                return ResourceManager.GetString("ConvertContextPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATIR TUTARI.
        /// </summary>
        public static string ConvertOrderGridLineAmount {
            get {
                return ResourceManager.GetString("ConvertOrderGridLineAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK KODU.
        /// </summary>
        public static string ConvertOrderGridProductCode {
            get {
                return ResourceManager.GetString("ConvertOrderGridProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRETİM EMRİ FİŞ NO.
        /// </summary>
        public static string ConvertOrderGridProductionOrder {
            get {
                return ResourceManager.GetString("ConvertOrderGridProductionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK AÇIKLAMASI.
        /// </summary>
        public static string ConvertOrderGridProductName {
            get {
                return ResourceManager.GetString("ConvertOrderGridProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURUM.
        /// </summary>
        public static string ConvertOrderGridPurchaseLineState {
            get {
                return ResourceManager.GetString("ConvertOrderGridPurchaseLineState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MİKTAR.
        /// </summary>
        public static string ConvertOrderGridQuantity {
            get {
                return ResourceManager.GetString("ConvertOrderGridQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİRİM FİYAT.
        /// </summary>
        public static string ConvertOrderGridUnitPrice {
            get {
                return ResourceManager.GetString("ConvertOrderGridUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİRİM SETİ.
        /// </summary>
        public static string ConvertOrderGridUnitSetCode {
            get {
                return ResourceManager.GetString("ConvertOrderGridUnitSetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEREL PARA BİRİMİ.
        /// </summary>
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yerel Para Birimi:.
        /// </summary>
        public static string CurrencyCodeLabel {
            get {
                return ResourceManager.GetString("CurrencyCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARA BİRİMİ KODU.
        /// </summary>
        public static string CurrencyModalGridCode {
            get {
                return ResourceManager.GetString("CurrencyModalGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARA BİRİMİ ADI.
        /// </summary>
        public static string CurrencyModalGridName {
            get {
                return ResourceManager.GetString("CurrencyModalGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Birimleri.
        /// </summary>
        public static string CurrencyModalTitle {
            get {
                return ResourceManager.GetString("CurrencyModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ HESAP KODU.
        /// </summary>
        public static string CurrentAccountCardCode {
            get {
                return ResourceManager.GetString("CurrentAccountCardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hesap Kodu:.
        /// </summary>
        public static string CurrentAccountCardCodeLabel {
            get {
                return ResourceManager.GetString("CurrentAccountCardCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ HESAP ÜNVANI.
        /// </summary>
        public static string CurrentAccountCardName {
            get {
                return ResourceManager.GetString("CurrentAccountCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hesap Ünvanı:.
        /// </summary>
        public static string CurrentAccountCardNameLabel {
            get {
                return ResourceManager.GetString("CurrentAccountCardNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ KOD.
        /// </summary>
        public static string CurrentAccountModalGridCode {
            get {
                return ResourceManager.GetString("CurrentAccountModalGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-POSTA.
        /// </summary>
        public static string CurrentAccountModalGridEmail {
            get {
                return ResourceManager.GetString("CurrentAccountModalGridEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARİ ÜNVAN.
        /// </summary>
        public static string CurrentAccountModalGridName {
            get {
                return ResourceManager.GetString("CurrentAccountModalGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLGİLİ.
        /// </summary>
        public static string CurrentAccountModalGridResponsible {
            get {
                return ResourceManager.GetString("CurrentAccountModalGridResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERGİ NUMARASI.
        /// </summary>
        public static string CurrentAccountModalGridTaxNumber {
            get {
                return ResourceManager.GetString("CurrentAccountModalGridTaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TELEFON (1).
        /// </summary>
        public static string CurrentAccountModalGridTel {
            get {
                return ResourceManager.GetString("CurrentAccountModalGridTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hesap Kartları.
        /// </summary>
        public static string CurrentAccountModalTitle {
            get {
                return ResourceManager.GetString("CurrentAccountModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARİH.
        /// </summary>
        public static string Date_ {
            get {
                return ResourceManager.GetString("Date_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih:.
        /// </summary>
        public static string Date_Label {
            get {
                return ResourceManager.GetString("Date_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğinize emin misiniz ?.
        /// </summary>
        public static string DeleteConfirmationDescriptionBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string DeleteConfirmationTitleBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın almaya dönüşen satın alma talepleri silinemez..
        /// </summary>
        public static string DeletePurchaseRequestConvertManager {
            get {
                return ResourceManager.GetString("DeletePurchaseRequestConvertManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylanan satın alma talep satırları silinemez..
        /// </summary>
        public static string DeletePurchaseRequestLineManager {
            get {
                return ResourceManager.GetString("DeletePurchaseRequestLineManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylanan satın alma talepleri silinemez..
        /// </summary>
        public static string DeletePurchaseRequestManager {
            get {
                return ResourceManager.GetString("DeletePurchaseRequestManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla silindi..
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama:.
        /// </summary>
        public static string Description_Label {
            get {
                return ResourceManager.GetString("Description_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim Tutarı:.
        /// </summary>
        public static string DiscountAmountLineLabel {
            get {
                return ResourceManager.GetString("DiscountAmountLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim Oranı:.
        /// </summary>
        public static string DiscountRateLineLabel {
            get {
                return ResourceManager.GetString("DiscountRateLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişe Dönüştür.
        /// </summary>
        public static string EditConvertOrderModalTitle {
            get {
                return ResourceManager.GetString("EditConvertOrderModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Talep Satırları.
        /// </summary>
        public static string EditLineModalTitle {
            get {
                return ResourceManager.GetString("EditLineModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Talep Fişleri.
        /// </summary>
        public static string EditModalTitle {
            get {
                return ResourceManager.GetString("EditModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onaylandı.
        /// </summary>
        public static string EnumApproved {
            get {
                return ResourceManager.GetString("EnumApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yerel Para Birimi.
        /// </summary>
        public static string EnumLocalCurrency {
            get {
                return ResourceManager.GetString("EnumLocalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kısmi Onaylandı.
        /// </summary>
        public static string EnumPartiallyApproved {
            get {
                return ResourceManager.GetString("EnumPartiallyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kısmi Satın Alma.
        /// </summary>
        public static string EnumPartialPurchase {
            get {
                return ResourceManager.GetString("EnumPartialPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma.
        /// </summary>
        public static string EnumPurchase {
            get {
                return ResourceManager.GetString("EnumPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Dövizi.
        /// </summary>
        public static string EnumTransactionCurrency {
            get {
                return ResourceManager.GetString("EnumTransactionCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklemede.
        /// </summary>
        public static string EnumWaiting {
            get {
                return ResourceManager.GetString("EnumWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kur Tutarı:.
        /// </summary>
        public static string ExchangeRateLabel {
            get {
                return ResourceManager.GetString("ExchangeRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEKLİF NO.
        /// </summary>
        public static string FicheNo {
            get {
                return ResourceManager.GetString("FicheNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif No:.
        /// </summary>
        public static string FicheNoLabel {
            get {
                return ResourceManager.GetString("FicheNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brüt Toplam:.
        /// </summary>
        public static string GrossAmountLabel {
            get {
                return ResourceManager.GetString("GrossAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satır Tutarı:.
        /// </summary>
        public static string LineAmountLineLabel {
            get {
                return ResourceManager.GetString("LineAmountLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satır Açıklaması:.
        /// </summary>
        public static string LineDescriptionLineLabel {
            get {
                return ResourceManager.GetString("LineDescriptionLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATIR TUTARI.
        /// </summary>
        public static string LineGridLineAmount {
            get {
                return ResourceManager.GetString("LineGridLineAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK KODU.
        /// </summary>
        public static string LineGridProductCode {
            get {
                return ResourceManager.GetString("LineGridProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRETİM EMRİ FİŞ NO.
        /// </summary>
        public static string LineGridProductionOrder {
            get {
                return ResourceManager.GetString("LineGridProductionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK AÇIKLAMASI.
        /// </summary>
        public static string LineGridProductName {
            get {
                return ResourceManager.GetString("LineGridProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KARŞILANMA DURUMU.
        /// </summary>
        public static string LineGridPurchaseRequestLineState {
            get {
                return ResourceManager.GetString("LineGridPurchaseRequestLineState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MİKTAR.
        /// </summary>
        public static string LineGridQuantity {
            get {
                return ResourceManager.GetString("LineGridQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİRİM FİYAT.
        /// </summary>
        public static string LineGridUnitPrice {
            get {
                return ResourceManager.GetString("LineGridUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİRİM SETİ.
        /// </summary>
        public static string LineGridUnitSetCode {
            get {
                return ResourceManager.GetString("LineGridUnitSetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satır Toplam Tutarı:.
        /// </summary>
        public static string LineTotalAmountLineLabel {
            get {
                return ResourceManager.GetString("LineTotalAmountLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Bekleyin...
        /// </summary>
        public static string LoadingCaption {
            get {
                return ResourceManager.GetString("LoadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar Yükleniyor...
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz kayıt {0} tarafından kullanılmaktadır..
        /// </summary>
        public static string MessagePopupInformationDescriptionBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        public static string MessagePopupInformationTitleBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malzeme İhtiyaç Planlaması (MRP).
        /// </summary>
        public static string MRPChildMenu {
            get {
                return ResourceManager.GetString("MRPChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRP KODU.
        /// </summary>
        public static string MRPCode {
            get {
                return ResourceManager.GetString("MRPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Almaya Dönüştür.
        /// </summary>
        public static string MRPContextConvertPurchase {
            get {
                return ResourceManager.GetString("MRPContextConvertPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Toplam:.
        /// </summary>
        public static string NetAmountLabel {
            get {
                return ResourceManager.GetString("NetAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖDEME PLANI KODU.
        /// </summary>
        public static string PaymentPlanModalGridCode {
            get {
                return ResourceManager.GetString("PaymentPlanModalGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VADE GÜNÜ.
        /// </summary>
        public static string PaymentPlanModalGridDays {
            get {
                return ResourceManager.GetString("PaymentPlanModalGridDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GECİKME VADE FARKI ORANI.
        /// </summary>
        public static string PaymentPlanModalGridDelayMat {
            get {
                return ResourceManager.GetString("PaymentPlanModalGridDelayMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖDEME PLANI AÇIKLAMASI.
        /// </summary>
        public static string PaymentPlanModalGridName {
            get {
                return ResourceManager.GetString("PaymentPlanModalGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Planları.
        /// </summary>
        public static string PaymentPlanModalTitle {
            get {
                return ResourceManager.GetString("PaymentPlanModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖDEME PLANI.
        /// </summary>
        public static string PaymentPlanName {
            get {
                return ResourceManager.GetString("PaymentPlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Planı:.
        /// </summary>
        public static string PaymentPlanNameLabel {
            get {
                return ResourceManager.GetString("PaymentPlanNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyatlandırma Dövizi.
        /// </summary>
        public static string PricingCurrencyLabel {
            get {
                return ResourceManager.GetString("PricingCurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string ProcessAdd {
            get {
                return ResourceManager.GetString("ProcessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string ProcessDelete {
            get {
                return ResourceManager.GetString("ProcessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string ProcessRefresh {
            get {
                return ResourceManager.GetString("ProcessRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Kodu:.
        /// </summary>
        public static string ProductCodeLineLabel {
            get {
                return ResourceManager.GetString("ProductCodeLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜRETİM EMRİ FİŞ NO.
        /// </summary>
        public static string ProductionOrderFicheNo {
            get {
                return ResourceManager.GetString("ProductionOrderFicheNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Emri:.
        /// </summary>
        public static string ProductionOrderFicheNoLabel {
            get {
                return ResourceManager.GetString("ProductionOrderFicheNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Emri:.
        /// </summary>
        public static string ProductionOrderFicheNoLineLabel {
            get {
                return ResourceManager.GetString("ProductionOrderFicheNoLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FİŞ NO.
        /// </summary>
        public static string ProductionOrderModalGridFiche {
            get {
                return ResourceManager.GetString("ProductionOrderModalGridFiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAMÜL KODU.
        /// </summary>
        public static string ProductionOrderModalGridFinishedCode {
            get {
                return ResourceManager.GetString("ProductionOrderModalGridFinishedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAMÜL AÇIKLAMASI.
        /// </summary>
        public static string ProductionOrderModalGridFinishedName {
            get {
                return ResourceManager.GetString("ProductionOrderModalGridFinishedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Emirleri.
        /// </summary>
        public static string ProductionOrderModalTitle {
            get {
                return ResourceManager.GetString("ProductionOrderModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK KODU.
        /// </summary>
        public static string ProductModalGridCode {
            get {
                return ResourceManager.GetString("ProductModalGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK AÇIKLAMASI.
        /// </summary>
        public static string ProductModalGridName {
            get {
                return ResourceManager.GetString("ProductModalGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Kartları.
        /// </summary>
        public static string ProductModalTitle {
            get {
                return ResourceManager.GetString("ProductModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Açıklaması:.
        /// </summary>
        public static string ProductNameLineLabel {
            get {
                return ResourceManager.GetString("ProductNameLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string PurchaseRequestContextAdd {
            get {
                return ResourceManager.GetString("PurchaseRequestContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string PurchaseRequestContextChange {
            get {
                return ResourceManager.GetString("PurchaseRequestContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişe Dönüştür.
        /// </summary>
        public static string PurchaseRequestContextConverttoOrder {
            get {
                return ResourceManager.GetString("PurchaseRequestContextConverttoOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string PurchaseRequestContextDelete {
            get {
                return ResourceManager.GetString("PurchaseRequestContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string PurchaseRequestContextRefresh {
            get {
                return ResourceManager.GetString("PurchaseRequestContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string PurchaseRequestLineContextAdd {
            get {
                return ResourceManager.GetString("PurchaseRequestLineContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string PurchaseRequestLineContextChange {
            get {
                return ResourceManager.GetString("PurchaseRequestLineContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string PurchaseRequestLineContextDelete {
            get {
                return ResourceManager.GetString("PurchaseRequestLineContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string PurchaseRequestLineContextRefresh {
            get {
                return ResourceManager.GetString("PurchaseRequestLineContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Talep Fişleri.
        /// </summary>
        public static string PurchaseRequestsChildMenu {
            get {
                return ResourceManager.GetString("PurchaseRequestsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Rezerve Miktarı:.
        /// </summary>
        public static string PurchaseReservedQuantityLineLabel {
            get {
                return ResourceManager.GetString("PurchaseReservedQuantityLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar:.
        /// </summary>
        public static string QuantityLineLabel {
            get {
                return ResourceManager.GetString("QuantityLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özel Kod:.
        /// </summary>
        public static string SpecialCodeLabel {
            get {
                return ResourceManager.GetString("SpecialCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEDARİKÇİ REFERANS NO.
        /// </summary>
        public static string SupplierReferanceNo {
            get {
                return ResourceManager.GetString("SupplierReferanceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim Toplamı:.
        /// </summary>
        public static string TotalDiscountAmountLabel {
            get {
                return ResourceManager.GetString("TotalDiscountAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDV Toplamı:.
        /// </summary>
        public static string TotalVatAmountLabel {
            get {
                return ResourceManager.GetString("TotalVatAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Tutar:.
        /// </summary>
        public static string TotalVatExcludedAmountLabel {
            get {
                return ResourceManager.GetString("TotalVatExcludedAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Dövizi İndirim Tutarı:.
        /// </summary>
        public static string TransactionExchangeDiscountAmountLineLabel {
            get {
                return ResourceManager.GetString("TransactionExchangeDiscountAmountLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Dövizi Brüt Toplam:.
        /// </summary>
        public static string TransactionExchangeGrossAmountLabel {
            get {
                return ResourceManager.GetString("TransactionExchangeGrossAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Dövizi:.
        /// </summary>
        public static string TransactionExchangeLabel {
            get {
                return ResourceManager.GetString("TransactionExchangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Dövizi Satır Tutarı:.
        /// </summary>
        public static string TransactionExchangeLineAmountLineLabel {
            get {
                return ResourceManager.GetString("TransactionExchangeLineAmountLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Dövizi Satır Toplam Tutarı:.
        /// </summary>
        public static string TransactionExchangeLineTotalAmountLineLabel {
            get {
                return ResourceManager.GetString("TransactionExchangeLineTotalAmountLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Dövizi Net Toplam:.
        /// </summary>
        public static string TransactionExchangeNetAmountLabel {
            get {
                return ResourceManager.GetString("TransactionExchangeNetAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Dövizi İndirim Toplamı:.
        /// </summary>
        public static string TransactionExchangeTotalDiscountAmountLabel {
            get {
                return ResourceManager.GetString("TransactionExchangeTotalDiscountAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Dövizi KDV Toplamı:.
        /// </summary>
        public static string TransactionExchangeTotalVatAmountLabel {
            get {
                return ResourceManager.GetString("TransactionExchangeTotalVatAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Dövizi Toplam Tutar:.
        /// </summary>
        public static string TransactionExchangeTotalVatExcludedAmountLabel {
            get {
                return ResourceManager.GetString("TransactionExchangeTotalVatExcludedAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Dövizi Birim Fiyat:.
        /// </summary>
        public static string TransactionExchangeUnitPriceLineLabel {
            get {
                return ResourceManager.GetString("TransactionExchangeUnitPriceLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Dövizi KDV Tutarı:.
        /// </summary>
        public static string TransactionExchangeVATamountLineLabel {
            get {
                return ResourceManager.GetString("TransactionExchangeVATamountLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz satın alma talebi, kalıcı olarak silinecektir..
        /// </summary>
        public static string UIConfirmationPopupMessageBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupMessageBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz satır kalıcı olarak silinecektir..
        /// </summary>
        public static string UIConfirmationPopupMessageLineBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupMessageLineBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikkat.
        /// </summary>
        public static string UIConfirmationPopupTitleBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Talep Fişleri.
        /// </summary>
        public static string UICurrentMenu {
            get {
                return ResourceManager.GetString("UICurrentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SatinAlmaTalepleri.
        /// </summary>
        public static string UIExportFileName {
            get {
                return ResourceManager.GetString("UIExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Talep Fişleri.
        /// </summary>
        public static string UIExportTitle {
            get {
                return ResourceManager.GetString("UIExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen onaylanmış satırlar, siparişe dönüştürüldü..
        /// </summary>
        public static string UIInformationConvertMessage {
            get {
                return ResourceManager.GetString("UIInformationConvertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgilendirme.
        /// </summary>
        public static string UIInformationConvertTitle {
            get {
                return ResourceManager.GetString("UIInformationConvertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Yönetimi &gt; Hareketler.
        /// </summary>
        public static string UIPreviousMenu {
            get {
                return ResourceManager.GetString("UIPreviousMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen tüm satırların durumu beklemededir. Beklemede olan satırlar, siparişe dönüştürülemez..
        /// </summary>
        public static string UIWarningConvertMessage {
            get {
                return ResourceManager.GetString("UIWarningConvertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        public static string UIWarningConvertTitle {
            get {
                return ResourceManager.GetString("UIWarningConvertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyatlandırma dövizi seçilmeden satır eklenemez..
        /// </summary>
        public static string UIWarningMessageBase {
            get {
                return ResourceManager.GetString("UIWarningMessageBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim seti seçilmeden satır kaydetme işlemi yapılamaz..
        /// </summary>
        public static string UIWarningPopupMessageBase1 {
            get {
                return ResourceManager.GetString("UIWarningPopupMessageBase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok kartı seçilmeden satır kaydetme işlemi yapılamaz..
        /// </summary>
        public static string UIWarningPopupMessageBase2 {
            get {
                return ResourceManager.GetString("UIWarningPopupMessageBase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar 0 olduğu için satır kaydetme işlemi yapılamamaktadır..
        /// </summary>
        public static string UIWarningPopupMessageBase3 {
            get {
                return ResourceManager.GetString("UIWarningPopupMessageBase3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyarı.
        /// </summary>
        public static string UIWarningTitleBase {
            get {
                return ResourceManager.GetString("UIWarningTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim Fiyat:.
        /// </summary>
        public static string UnitPriceLineLabel {
            get {
                return ResourceManager.GetString("UnitPriceLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim Seti Kodu:.
        /// </summary>
        public static string UnitSetCodeLineLabel {
            get {
                return ResourceManager.GetString("UnitSetCodeLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİRİM SETİ KODU.
        /// </summary>
        public static string UnitSetModalGridCode {
            get {
                return ResourceManager.GetString("UnitSetModalGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİRİM SETİ AÇIKLAMASI.
        /// </summary>
        public static string UnitSetModalGridName {
            get {
                return ResourceManager.GetString("UnitSetModalGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim Setleri.
        /// </summary>
        public static string UnitSetModalTitle {
            get {
                return ResourceManager.GetString("UnitSetModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı numaralı bir kayıt bulunmaktadır..
        /// </summary>
        public static string UpdateControlManager {
            get {
                return ResourceManager.GetString("UpdateControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen şube seçin..
        /// </summary>
        public static string ValidatorBranchID {
            get {
                return ResourceManager.GetString("ValidatorBranchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen talep numarasını yazın..
        /// </summary>
        public static string ValidatorCodeEmpty {
            get {
                return ResourceManager.GetString("ValidatorCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talep numarası 17 karakterden fazla olamaz..
        /// </summary>
        public static string ValidatorCodeMaxLength {
            get {
                return ResourceManager.GetString("ValidatorCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen para birimi seçin..
        /// </summary>
        public static string ValidatorCurrencyID {
            get {
                return ResourceManager.GetString("ValidatorCurrencyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen cari hesap seçin..
        /// </summary>
        public static string ValidatorCurrentAccountID {
            get {
                return ResourceManager.GetString("ValidatorCurrentAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen tarihi seçin..
        /// </summary>
        public static string ValidatorDate {
            get {
                return ResourceManager.GetString("ValidatorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen kur tutarını yazın..
        /// </summary>
        public static string ValidatorExchangeRateEmpty {
            get {
                return ResourceManager.GetString("ValidatorExchangeRateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kur tutarı 0&apos;dan büyük olmalıdır..
        /// </summary>
        public static string ValidatorExchangeRateMin {
            get {
                return ResourceManager.GetString("ValidatorExchangeRateMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen talep geçerlilik tarihi seçin..
        /// </summary>
        public static string ValidatorValidityDate {
            get {
                return ResourceManager.GetString("ValidatorValidityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen depo seçin..
        /// </summary>
        public static string ValidatorWarehouseID {
            get {
                return ResourceManager.GetString("ValidatorWarehouseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerlilik Tarihi:.
        /// </summary>
        public static string ValidityDate_Label {
            get {
                return ResourceManager.GetString("ValidityDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDV Tutarı:.
        /// </summary>
        public static string VATamountLineLabel {
            get {
                return ResourceManager.GetString("VATamountLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KDV Oranı:.
        /// </summary>
        public static string VATrateLineLabel {
            get {
                return ResourceManager.GetString("VATrateLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekleyen Miktar:.
        /// </summary>
        public static string WaitingQuantityLineLabel {
            get {
                return ResourceManager.GetString("WaitingQuantityLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPO KODU.
        /// </summary>
        public static string WarehouseCode {
            get {
                return ResourceManager.GetString("WarehouseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPO KODU.
        /// </summary>
        public static string WarehouseModalGridCode {
            get {
                return ResourceManager.GetString("WarehouseModalGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPO ADI.
        /// </summary>
        public static string WarehouseModalGridName {
            get {
                return ResourceManager.GetString("WarehouseModalGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depolar.
        /// </summary>
        public static string WarehouseModalTitle {
            get {
                return ResourceManager.GetString("WarehouseModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depo:.
        /// </summary>
        public static string WarehouseNameLabel {
            get {
                return ResourceManager.GetString("WarehouseNameLabel", resourceCulture);
            }
        }
    }
}
