//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsiErp.Localizations.Resources.ProductsOperations.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductsOperationsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductsOperationsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsiErp.Localizations.Resources.ProductsOperations.Page.ProductsOperationsResource" +
                            "", typeof(ProductsOperationsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayar ve Kontrol Süresi:.
        /// </summary>
        public static string AdjustmentAndControlTimeLineLabel {
            get {
                return ResourceManager.GetString("AdjustmentAndControlTimeLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatif:.
        /// </summary>
        public static string AlternativeLineLabel {
            get {
                return ResourceManager.GetString("AlternativeLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERASYON KODU.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı kodlu bir kayıt bulunmaktadır..
        /// </summary>
        public static string CodeControlManager {
            get {
                return ResourceManager.GetString("CodeControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasyon Kodu:.
        /// </summary>
        public static string CodeLabel {
            get {
                return ResourceManager.GetString("CodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string ContextAdd {
            get {
                return ResourceManager.GetString("ContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string ContextChange {
            get {
                return ResourceManager.GetString("ContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string ContextDelete {
            get {
                return ResourceManager.GetString("ContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string ContextRefresh {
            get {
                return ResourceManager.GetString("ContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğinize emin misiniz ?.
        /// </summary>
        public static string DeleteConfirmationDescriptionBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string DeleteConfirmationTitleBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla silindi..
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Operasyon Satırları.
        /// </summary>
        public static string EditLineModal {
            get {
                return ResourceManager.GetString("EditLineModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Operasyon Kayıtları.
        /// </summary>
        public static string EditModalTitle {
            get {
                return ResourceManager.GetString("EditModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiflik:.
        /// </summary>
        public static string IsActiveLabel {
            get {
                return ResourceManager.GetString("IsActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AYAR KONTROL SÜRESİ.
        /// </summary>
        public static string LineGridAdjustment {
            get {
                return ResourceManager.GetString("LineGridAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTERNATİF.
        /// </summary>
        public static string LineGridAlternative {
            get {
                return ResourceManager.GetString("LineGridAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERASYON SÜRESİ.
        /// </summary>
        public static string LineGridOperationTime {
            get {
                return ResourceManager.GetString("LineGridOperationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖNCELİK.
        /// </summary>
        public static string LineGridPriority {
            get {
                return ResourceManager.GetString("LineGridPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İŞLEM ADET.
        /// </summary>
        public static string LineGridProcessQuantity {
            get {
                return ResourceManager.GetString("LineGridProcessQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTASYON KODU.
        /// </summary>
        public static string LineGridStationCode {
            get {
                return ResourceManager.GetString("LineGridStationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTASYON AÇIKLAMASI.
        /// </summary>
        public static string LineGridStationName {
            get {
                return ResourceManager.GetString("LineGridStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Bekleyin...
        /// </summary>
        public static string LoadingCaption {
            get {
                return ResourceManager.GetString("LoadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar Yükleniyor...
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz kayıt {0} tarafından kullanılmaktadır..
        /// </summary>
        public static string MessagePopupInformationDescriptionBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        public static string MessagePopupInformationTitleBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERASYON AÇIKLAMASI.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasyon Açıklaması:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasyon Süresi:.
        /// </summary>
        public static string OperationTimeLineLabel {
            get {
                return ResourceManager.GetString("OperationTimeLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öncelik:.
        /// </summary>
        public static string PriorityLineLabel {
            get {
                return ResourceManager.GetString("PriorityLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Adet:.
        /// </summary>
        public static string ProcessQuantityLineLabel {
            get {
                return ResourceManager.GetString("ProcessQuantityLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAMÜL KODU.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Kodu:.
        /// </summary>
        public static string ProductCodeLabel {
            get {
                return ResourceManager.GetString("ProductCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK KODU.
        /// </summary>
        public static string ProductModalGridCode {
            get {
                return ResourceManager.GetString("ProductModalGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK AÇIKLAMASI.
        /// </summary>
        public static string ProductModalGridName {
            get {
                return ResourceManager.GetString("ProductModalGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Kartları.
        /// </summary>
        public static string ProductModalTitle {
            get {
                return ResourceManager.GetString("ProductModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Açıklaması:.
        /// </summary>
        public static string ProductNameLabel {
            get {
                return ResourceManager.GetString("ProductNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyon Kodu:.
        /// </summary>
        public static string StationCodeLineLabel {
            get {
                return ResourceManager.GetString("StationCodeLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTASYON KODU.
        /// </summary>
        public static string StationModalGridCode {
            get {
                return ResourceManager.GetString("StationModalGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTASYON AÇIKLAMASI.
        /// </summary>
        public static string StationModalGridName {
            get {
                return ResourceManager.GetString("StationModalGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş İstasyonları.
        /// </summary>
        public static string StationModalTitle {
            get {
                return ResourceManager.GetString("StationModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyon Açıklaması:.
        /// </summary>
        public static string StationNameLineLabel {
            get {
                return ResourceManager.GetString("StationNameLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şablon Operasyon:.
        /// </summary>
        public static string TemplateOperationCodeLabel {
            get {
                return ResourceManager.GetString("TemplateOperationCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞABLON OPERASYON KODU.
        /// </summary>
        public static string TemplateOprModalGridCode {
            get {
                return ResourceManager.GetString("TemplateOprModalGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŞABLON OPERASYON AÇIKLAMASI.
        /// </summary>
        public static string TemplateOprModalGridName {
            get {
                return ResourceManager.GetString("TemplateOprModalGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şablon Operasyonlar.
        /// </summary>
        public static string TemplateOprModalTitle {
            get {
                return ResourceManager.GetString("TemplateOprModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz ürüne özel operasyon kalıcı olarak silinecektir..
        /// </summary>
        public static string UIConfirmationPopupMessageBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupMessageBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz satır kalıcı olarak silinecektir..
        /// </summary>
        public static string UIConfirmationPopupMessageLineBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupMessageLineBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikkat.
        /// </summary>
        public static string UIConfirmationPopupTitleBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Operasyon Kayıtları.
        /// </summary>
        public static string UICurrentMenu {
            get {
                return ResourceManager.GetString("UICurrentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UrunOprKayitlari.
        /// </summary>
        public static string UIExportFileName {
            get {
                return ResourceManager.GetString("UIExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Operasyon Kayıtları.
        /// </summary>
        public static string UIExportTitle {
            get {
                return ResourceManager.GetString("UIExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Yönetimi &gt; Ana Kayıtlar &gt; Operasyonlar.
        /// </summary>
        public static string UIPreviousMenu {
            get {
                return ResourceManager.GetString("UIPreviousMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı kodlu bir kayıt bulunmaktadır..
        /// </summary>
        public static string UpdateControlManager {
            get {
                return ResourceManager.GetString("UpdateControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen operasyon kodunu yazın..
        /// </summary>
        public static string ValidatorCodeEmpty {
            get {
                return ResourceManager.GetString("ValidatorCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasyon kodu, 17 karakterden fazla olamaz..
        /// </summary>
        public static string ValidatorCodeMaxLenght {
            get {
                return ResourceManager.GetString("ValidatorCodeMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen operasyon açıklaması yazın..
        /// </summary>
        public static string ValidatorNameEmpty {
            get {
                return ResourceManager.GetString("ValidatorNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasyon açıklaması, 200 karakterden fazla olamaz..
        /// </summary>
        public static string ValidatorNameMaxLenght {
            get {
                return ResourceManager.GetString("ValidatorNameMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen ürün seçin..
        /// </summary>
        public static string ValidatorProductID {
            get {
                return ResourceManager.GetString("ValidatorProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İŞ MERKEZİ KODU.
        /// </summary>
        public static string WorkCenterCode {
            get {
                return ResourceManager.GetString("WorkCenterCode", resourceCulture);
            }
        }
    }
}
