//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsiErp.Localizations.Resources.PlannedMaintenances.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlannedMaintenancesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlannedMaintenancesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsiErp.Localizations.Resources.PlannedMaintenances.Page.PlannedMaintenancesResour" +
                            "ce", typeof(PlannedMaintenancesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı numaralı bir kayıt bulunmaktadır..
        /// </summary>
        public static string CodeControlManager {
            get {
                return ResourceManager.GetString("CodeControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string ContextAdd {
            get {
                return ResourceManager.GetString("ContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string ContextChange {
            get {
                return ResourceManager.GetString("ContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string ContextDelete {
            get {
                return ResourceManager.GetString("ContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string ContextRefresh {
            get {
                return ResourceManager.GetString("ContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğinize emin misiniz ?.
        /// </summary>
        public static string DeleteConfirmationDescriptionBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string DeleteConfirmationTitleBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla silindi..
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Bekleyin...
        /// </summary>
        public static string LoadingCaption {
            get {
                return ResourceManager.GetString("LoadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar Yükleniyor...
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz kayıt {0} tarafından kullanılmaktadır..
        /// </summary>
        public static string MessagePopupInformationDescriptionBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        public static string MessagePopupInformationTitleBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı numaralı bir kayıt bulunmaktadır..
        /// </summary>
        public static string UpdateControlManager {
            get {
                return ResourceManager.GetString("UpdateControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bakım kayıt numarasını yazın..
        /// </summary>
        public static string ValidatorCodeEmpty {
            get {
                return ResourceManager.GetString("ValidatorCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakım kayıt numarası, 17 karakterden fazla olamaz..
        /// </summary>
        public static string ValidatorCodeMaxLenght {
            get {
                return ResourceManager.GetString("ValidatorCodeMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bakım türü seçin..
        /// </summary>
        public static string ValidatorPediodID {
            get {
                return ResourceManager.GetString("ValidatorPediodID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen istasyon seçin..
        /// </summary>
        public static string ValidatorStationID {
            get {
                return ResourceManager.GetString("ValidatorStationID", resourceCulture);
            }
        }
    }
}
