//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsiErp.Localizations.Resources.PackingLists.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PackingListsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackingListsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsiErp.Localizations.Resources.PackingLists.Page.PackingListsResource", typeof(PackingListsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı numaralı bir kayıt bulunmaktadır..
        /// </summary>
        public static string CodeControlManager {
            get {
                return ResourceManager.GetString("CodeControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğinize emin misiniz ?.
        /// </summary>
        public static string DeleteConfirmationDescriptionBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string DeleteConfirmationTitleBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hareket gören kayıtlar silinemez..
        /// </summary>
        public static string DeleteControlManager {
            get {
                return ResourceManager.GetString("DeleteControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla silindi..
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeki Listeleri.
        /// </summary>
        public static string EditModalTitle {
            get {
                return ResourceManager.GetString("EditModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamamlandı.
        /// </summary>
        public static string EnumCompleted {
            get {
                return ResourceManager.GetString("EnumCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komple TIR.
        /// </summary>
        public static string EnumCompleteTIR {
            get {
                return ResourceManager.GetString("EnumCompleteTIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex-Works İstanbul (€).
        /// </summary>
        public static string EnumExWorks {
            get {
                return ResourceManager.GetString("EnumExWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOB İstanbul (€).
        /// </summary>
        public static string EnumFOB {
            get {
                return ResourceManager.GetString("EnumFOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsiyel TIR.
        /// </summary>
        public static string EnumPartialTIR {
            get {
                return ResourceManager.GetString("EnumPartialTIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazırlanıyor.
        /// </summary>
        public static string EnumPreparing {
            get {
                return ResourceManager.GetString("EnumPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sevk Edildi.
        /// </summary>
        public static string EnumTransferred {
            get {
                return ResourceManager.GetString("EnumTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CekiListeleri.
        /// </summary>
        public static string ExportFileName {
            get {
                return ResourceManager.GetString("ExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeki Listeleri.
        /// </summary>
        public static string ExportTitle {
            get {
                return ResourceManager.GetString("ExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Bekleyin...
        /// </summary>
        public static string LoadingCaption {
            get {
                return ResourceManager.GetString("LoadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar Yükleniyor...
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz kayıt {0} tarafından kullanılmaktadır..
        /// </summary>
        public static string MessagePopupInformationDescriptionBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        public static string MessagePopupInformationTitleBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string PackingListsContextAdd {
            get {
                return ResourceManager.GetString("PackingListsContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string PackingListsContextChange {
            get {
                return ResourceManager.GetString("PackingListsContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string PackingListsContextDelete {
            get {
                return ResourceManager.GetString("PackingListsContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string PackingListsContextRefresh {
            get {
                return ResourceManager.GetString("PackingListsContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sevkiyat Yönetimi &gt; Hareketler.
        /// </summary>
        public static string UIPreviousMenu {
            get {
                return ResourceManager.GetString("UIPreviousMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı kodlu bir kayıt bulunmaktadır..
        /// </summary>
        public static string UpdateControlManager {
            get {
                return ResourceManager.GetString("UpdateControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen fatura tarihi seçin..
        /// </summary>
        public static string ValidatorBillDate {
            get {
                return ResourceManager.GetString("ValidatorBillDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen çeki listesi numarası 2&apos;yi yazın..
        /// </summary>
        public static string ValidatorCode2Empty {
            get {
                return ResourceManager.GetString("ValidatorCode2Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeki listesi numarası 2, 250 karakterden fazla olamaz..
        /// </summary>
        public static string ValidatorCode2MaxLenght {
            get {
                return ResourceManager.GetString("ValidatorCode2MaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen çeki listesi numarasını yazın..
        /// </summary>
        public static string ValidatorCodeEmpty {
            get {
                return ResourceManager.GetString("ValidatorCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeki listesi numarası 17 karakterden fazla olamaz..
        /// </summary>
        public static string ValidatorCodeMaxLenght {
            get {
                return ResourceManager.GetString("ValidatorCodeMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen teslimat tarihi seçin..
        /// </summary>
        public static string ValidatorDeliveryDate {
            get {
                return ResourceManager.GetString("ValidatorDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen yükleme tarihi seçin..
        /// </summary>
        public static string ValidatorLoadingDate {
            get {
                return ResourceManager.GetString("ValidatorLoadingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen çeki listesi durumu seçin..
        /// </summary>
        public static string ValidatorPackingListStateEmpty {
            get {
                return ResourceManager.GetString("ValidatorPackingListStateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen çeki listesi durumu seçin..
        /// </summary>
        public static string ValidatorPackingListStateMax {
            get {
                return ResourceManager.GetString("ValidatorPackingListStateMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen çeki listesi durumu seçin..
        /// </summary>
        public static string ValidatorPackingListStateMin {
            get {
                return ResourceManager.GetString("ValidatorPackingListStateMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen ödeme tarihi seçin..
        /// </summary>
        public static string ValidatorPaymentDate {
            get {
                return ResourceManager.GetString("ValidatorPaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen gönderilen seçin..
        /// </summary>
        public static string ValidatorRecieverID {
            get {
                return ResourceManager.GetString("ValidatorRecieverID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen satış şekli seçin..
        /// </summary>
        public static string ValidatorSalesTypeEmpty {
            get {
                return ResourceManager.GetString("ValidatorSalesTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen satış şekli seçin..
        /// </summary>
        public static string ValidatorSalesTypeMax {
            get {
                return ResourceManager.GetString("ValidatorSalesTypeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen satış şekli seçin..
        /// </summary>
        public static string ValidatorSalesTypeMin {
            get {
                return ResourceManager.GetString("ValidatorSalesTypeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen tır şekli seçin..
        /// </summary>
        public static string ValidatorTIRTypeEmpty {
            get {
                return ResourceManager.GetString("ValidatorTIRTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen tır şekli seçin..
        /// </summary>
        public static string ValidatorTIRTypeMax {
            get {
                return ResourceManager.GetString("ValidatorTIRTypeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen tır şekli seçin..
        /// </summary>
        public static string ValidatorTIRTypeMin {
            get {
                return ResourceManager.GetString("ValidatorTIRTypeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen gönderici seçin..
        /// </summary>
        public static string ValidatorTransmitterID {
            get {
                return ResourceManager.GetString("ValidatorTransmitterID", resourceCulture);
            }
        }
    }
}
