//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsiErp.Localizations.Resources.Calendars.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CalendarsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalendarsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsiErp.Localizations.Resources.Calendars.Page.CalendarsResource", typeof(CalendarsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AÇIKLAMA.
        /// </summary>
        public static string _Description {
            get {
                return ResourceManager.GetString("_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar:.
        /// </summary>
        public static string AmountLineLabel {
            get {
                return ResourceManager.GetString("AmountLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Takvimi.
        /// </summary>
        public static string CalendarChildMenu {
            get {
                return ResourceManager.GetString("CalendarChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string CalendarContextAdd {
            get {
                return ResourceManager.GetString("CalendarContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string CalendarContextChange {
            get {
                return ResourceManager.GetString("CalendarContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string CalendarContextDelete {
            get {
                return ResourceManager.GetString("CalendarContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string CalendarContextRefresh {
            get {
                return ResourceManager.GetString("CalendarContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takvimi Görüntüle.
        /// </summary>
        public static string CalendarContextShowCalendar {
            get {
                return ResourceManager.GetString("CalendarContextShowCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string CalendarDayContextDelete {
            get {
                return ResourceManager.GetString("CalendarDayContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARİH.
        /// </summary>
        public static string CalendarDayDate {
            get {
                return ResourceManager.GetString("CalendarDayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURUM.
        /// </summary>
        public static string CalendarDayStateEnum {
            get {
                return ResourceManager.GetString("CalendarDayStateEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakım Bilgileri.
        /// </summary>
        public static string CalendarLineContextMaintenance {
            get {
                return ResourceManager.GetString("CalendarLineContextMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazla Mesai Güncelle.
        /// </summary>
        public static string CalendarLineContextOverTime {
            get {
                return ResourceManager.GetString("CalendarLineContextOverTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Durumunu Güncelle.
        /// </summary>
        public static string CalendarLineContextWorkStatus {
            get {
                return ResourceManager.GetString("CalendarLineContextWorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakımı Yapan:.
        /// </summary>
        public static string CaregiverLabel {
            get {
                return ResourceManager.GetString("CaregiverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAKVİM KODU.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı kodlu bir kayıt bulunmaktadır..
        /// </summary>
        public static string CodeControlManager {
            get {
                return ResourceManager.GetString("CodeControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takvim Kodu:.
        /// </summary>
        public static string CodeLabel {
            get {
                return ResourceManager.GetString("CodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamamlanma Tarihi:.
        /// </summary>
        public static string CompletionDateLabel {
            get {
                return ResourceManager.GetString("CompletionDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih 2:.
        /// </summary>
        public static string Date_2Label {
            get {
                return ResourceManager.GetString("Date_2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih 1:.
        /// </summary>
        public static string Date_Label {
            get {
                return ResourceManager.GetString("Date_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takvim Yılı:.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takvim Yılı.
        /// </summary>
        public static string DateYear {
            get {
                return ResourceManager.GetString("DateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARİH.
        /// </summary>
        public static string DayDate {
            get {
                return ResourceManager.GetString("DayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÜR.
        /// </summary>
        public static string DayStatus {
            get {
                return ResourceManager.GetString("DayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün Türünü Belirle.
        /// </summary>
        public static string DayTypeButton {
            get {
                return ResourceManager.GetString("DayTypeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string DayTypeContextAdd {
            get {
                return ResourceManager.GetString("DayTypeContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string DayTypeContextChange {
            get {
                return ResourceManager.GetString("DayTypeContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string DayTypeContextDelete {
            get {
                return ResourceManager.GetString("DayTypeContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string DayTypeContextRefresh {
            get {
                return ResourceManager.GetString("DayTypeContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün Türünü Belirleme İşlemleri.
        /// </summary>
        public static string DayTypeCrudModalTitle {
            get {
                return ResourceManager.GetString("DayTypeCrudModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tür:.
        /// </summary>
        public static string DayTypeLabel {
            get {
                return ResourceManager.GetString("DayTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün Türünü Belirle.
        /// </summary>
        public static string DayTypeModalTitle {
            get {
                return ResourceManager.GetString("DayTypeModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek istediğinize emin misiniz ?.
        /// </summary>
        public static string DeleteConfirmationDescriptionBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string DeleteConfirmationTitleBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hareket gören kayıtlar silinemez..
        /// </summary>
        public static string DeleteControlManager {
            get {
                return ResourceManager.GetString("DeleteControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt başarıyla silindi..
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama:.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapıldı.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Takvimi.
        /// </summary>
        public static string EditModalTitle {
            get {
                return ResourceManager.GetString("EditModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi:.
        /// </summary>
        public static string EndDateLineLabel {
            get {
                return ResourceManager.GetString("EndDateLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yarım Gün.
        /// </summary>
        public static string HalfDay {
            get {
                return ResourceManager.GetString("HalfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tatil.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talimat Açıklaması:.
        /// </summary>
        public static string InstructionDescriptionLineLabel {
            get {
                return ResourceManager.GetString("InstructionDescriptionLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiflik:.
        /// </summary>
        public static string IsActiveLabel {
            get {
                return ResourceManager.GetString("IsActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih Aralığı:.
        /// </summary>
        public static string isDateSpanLabel {
            get {
                return ResourceManager.GetString("isDateSpanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLANLI.
        /// </summary>
        public static string IsPlanned {
            get {
                return ResourceManager.GetString("IsPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlı:.
        /// </summary>
        public static string IsPlannedLabel {
            get {
                return ResourceManager.GetString("IsPlannedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlanan Takvim:.
        /// </summary>
        public static string IsPlannedLineLabel {
            get {
                return ResourceManager.GetString("IsPlannedLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÇALIŞILABİLİR SÜRE.
        /// </summary>
        public static string LineAvailableTime {
            get {
                return ResourceManager.GetString("LineAvailableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARİH.
        /// </summary>
        public static string LineDate {
            get {
                return ResourceManager.GetString("LineDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MİKTAR.
        /// </summary>
        public static string LineGridAmount {
            get {
                return ResourceManager.GetString("LineGridAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AÇIKLAMA.
        /// </summary>
        public static string LineGridInstructionDescription {
            get {
                return ResourceManager.GetString("LineGridInstructionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATIR NO.
        /// </summary>
        public static string LineGridLineNr {
            get {
                return ResourceManager.GetString("LineGridLineNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT.
        /// </summary>
        public static string LineGridMaintenanceNote {
            get {
                return ResourceManager.GetString("LineGridMaintenanceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOK KODU.
        /// </summary>
        public static string LineGridProductCode {
            get {
                return ResourceManager.GetString("LineGridProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİRİM SETİ.
        /// </summary>
        public static string LineGridUnitSetCode {
            get {
                return ResourceManager.GetString("LineGridUnitSetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAKIM TÜRÜ.
        /// </summary>
        public static string LineMaintenanceType {
            get {
                return ResourceManager.GetString("LineMaintenanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş İstasyonu Vardiya Satırları.
        /// </summary>
        public static string LineModalTitle {
            get {
                return ResourceManager.GetString("LineModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLANLI DURUŞ SÜRESİ.
        /// </summary>
        public static string LinePlannedHaltTimes {
            get {
                return ResourceManager.GetString("LinePlannedHaltTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLANLI BAKIM SÜRESİ.
        /// </summary>
        public static string LinePlannedMaintenanceTime {
            get {
                return ResourceManager.GetString("LinePlannedMaintenanceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARDİYA ADI.
        /// </summary>
        public static string LineShiftName {
            get {
                return ResourceManager.GetString("LineShiftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARDİYA SÜRESİ.
        /// </summary>
        public static string LineShiftTime {
            get {
                return ResourceManager.GetString("LineShiftTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAZLA MESAİ SÜRESİ.
        /// </summary>
        public static string LineShitOvertime {
            get {
                return ResourceManager.GetString("LineShitOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTASYON KODU.
        /// </summary>
        public static string LineStationCode {
            get {
                return ResourceManager.GetString("LineStationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İSTASYON AÇIKLAMASI.
        /// </summary>
        public static string LineStationName {
            get {
                return ResourceManager.GetString("LineStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÇALIŞMA DURUMU.
        /// </summary>
        public static string LineWorkStatus {
            get {
                return ResourceManager.GetString("LineWorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Bekleyin...
        /// </summary>
        public static string LoadingCaption {
            get {
                return ResourceManager.GetString("LoadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükleme Günü.
        /// </summary>
        public static string LoadingDay {
            get {
                return ResourceManager.GetString("LoadingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlar Yükleniyor...
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string MaintenaceInfosContextAdd {
            get {
                return ResourceManager.GetString("MaintenaceInfosContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string MaintenaceInfosContextChange {
            get {
                return ResourceManager.GetString("MaintenaceInfosContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string MaintenaceInfosContextDelete {
            get {
                return ResourceManager.GetString("MaintenaceInfosContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string MaintenaceInfosContextRefresh {
            get {
                return ResourceManager.GetString("MaintenaceInfosContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakım.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlı / Önleyici Bakım Kayıtları .
        /// </summary>
        public static string MaintenanceCrudModalTitle {
            get {
                return ResourceManager.GetString("MaintenanceCrudModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlı / Önleyici Bakım Kayıt Satırları.
        /// </summary>
        public static string MaintenanceLineEditModalTitle {
            get {
                return ResourceManager.GetString("MaintenanceLineEditModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAKIMI YAPAN.
        /// </summary>
        public static string MaintenanceModalCaregiver {
            get {
                return ResourceManager.GetString("MaintenanceModalCaregiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAKIM PERİYODU.
        /// </summary>
        public static string MaintenanceModalPeriodName {
            get {
                return ResourceManager.GetString("MaintenanceModalPeriodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLANLANAN BAKIM TARİHİ.
        /// </summary>
        public static string MaintenanceModalPlannedDate {
            get {
                return ResourceManager.GetString("MaintenanceModalPlannedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAYIT NO.
        /// </summary>
        public static string MaintenanceModalRegistrationNo {
            get {
                return ResourceManager.GetString("MaintenanceModalRegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAŞLANGIÇ TARİHİ.
        /// </summary>
        public static string MaintenanceModalStartDate {
            get {
                return ResourceManager.GetString("MaintenanceModalStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İŞ İSTASYONU.
        /// </summary>
        public static string MaintenanceModalStationCode {
            get {
                return ResourceManager.GetString("MaintenanceModalStationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not:.
        /// </summary>
        public static string MaintenanceNoteLineLabel {
            get {
                return ResourceManager.GetString("MaintenanceNoteLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz kayıt {0} tarafından kullanılmaktadır..
        /// </summary>
        public static string MessagePopupInformationDescriptionBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        public static string MessagePopupInformationTitleBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAKVİM ADI.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takvim Adı:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılmadı.
        /// </summary>
        public static string NotDone {
            get {
                return ResourceManager.GetString("NotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not:.
        /// </summary>
        public static string Note_Label {
            get {
                return ResourceManager.GetString("Note_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakımı Yapan Kişi Sayısı:.
        /// </summary>
        public static string NumberofCaregiversLabel {
            get {
                return ResourceManager.GetString("NumberofCaregiversLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerçekleşen Süre:.
        /// </summary>
        public static string OccuredTimeLabel {
            get {
                return ResourceManager.GetString("OccuredTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resmi Tatil.
        /// </summary>
        public static string OfficialHoliday {
            get {
                return ResourceManager.GetString("OfficialHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resmi Tatil Günü:.
        /// </summary>
        public static string OfficialHolidayLabel {
            get {
                return ResourceManager.GetString("OfficialHolidayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arızi Kısıt.
        /// </summary>
        public static string PartialFailure {
            get {
                return ResourceManager.GetString("PartialFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör Kısıtı.
        /// </summary>
        public static string PartialOperator {
            get {
                return ResourceManager.GetString("PartialOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Kısıtı.
        /// </summary>
        public static string PartialProduction {
            get {
                return ResourceManager.GetString("PartialProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakım Periyodu:.
        /// </summary>
        public static string PeriodNameLabel {
            get {
                return ResourceManager.GetString("PeriodNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periyot Süresi:.
        /// </summary>
        public static string PeriodTimeLabel {
            get {
                return ResourceManager.GetString("PeriodTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma durumu seçin..
        /// </summary>
        public static string PlaceHolderWorkState {
            get {
                return ResourceManager.GetString("PlaceHolderWorkState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlanan Bakım Tarihi:.
        /// </summary>
        public static string PlannedDateLabel {
            get {
                return ResourceManager.GetString("PlannedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlı / Önleyici Bakım Kayıtları.
        /// </summary>
        public static string PlannedMaintenanceModalTitle {
            get {
                return ResourceManager.GetString("PlannedMaintenanceModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlanan Bakım Süresi:.
        /// </summary>
        public static string PlannedTimeLabel {
            get {
                return ResourceManager.GetString("PlannedTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Kodu:.
        /// </summary>
        public static string ProductCodeLineLabel {
            get {
                return ResourceManager.GetString("ProductCodeLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Açıklaması:.
        /// </summary>
        public static string ProductNameLineLabel {
            get {
                return ResourceManager.GetString("ProductNameLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Numarası:.
        /// </summary>
        public static string RegistrationNoLabel {
            get {
                return ResourceManager.GetString("RegistrationNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalan Süre:.
        /// </summary>
        public static string RemainingTimeLabel {
            get {
                return ResourceManager.GetString("RemainingTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Takvimi.
        /// </summary>
        public static string SchedularModalTitle {
            get {
                return ResourceManager.GetString("SchedularModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hepsini Seç.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstasyonları Planla.
        /// </summary>
        public static string SelectedStationPlan {
            get {
                return ResourceManager.GetString("SelectedStationPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazla Mesai:.
        /// </summary>
        public static string ShiftOverTimeLineLabel {
            get {
                return ResourceManager.GetString("ShiftOverTimeLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakım Bilgilerini Görüntüle.
        /// </summary>
        public static string ShowMaintenanceInfosButton {
            get {
                return ResourceManager.GetString("ShowMaintenanceInfosButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi:.
        /// </summary>
        public static string StartDateLabel {
            get {
                return ResourceManager.GetString("StartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi:.
        /// </summary>
        public static string StartDateLineLabel {
            get {
                return ResourceManager.GetString("StartDateLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş İstasyonu:.
        /// </summary>
        public static string StationCodeLabel {
            get {
                return ResourceManager.GetString("StationCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş İstasyonu Fazla Mesai Bilgileri.
        /// </summary>
        public static string StationShiftModalOverTimeTitle {
            get {
                return ResourceManager.GetString("StationShiftModalOverTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş İstasyonu Vardiya Bilgileri.
        /// </summary>
        public static string StationShiftModalTitle {
            get {
                return ResourceManager.GetString("StationShiftModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş İstasyonları.
        /// </summary>
        public static string StationsModalTitle {
            get {
                return ResourceManager.GetString("StationsModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum:.
        /// </summary>
        public static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen kayıt silinecektir..
        /// </summary>
        public static string UIConfirmationPopupMessageBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupMessageBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen kayıt silinecektir..
        /// </summary>
        public static string UIConfirmationPopupMessageDayTypeBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupMessageDayTypeBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen kayıt silinecektir..
        /// </summary>
        public static string UIConfirmationPopupMessageMaintenanceBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupMessageMaintenanceBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        public static string UIConfirmationPopupTitleBase {
            get {
                return ResourceManager.GetString("UIConfirmationPopupTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Takvimi.
        /// </summary>
        public static string UICurrentMenu {
            get {
                return ResourceManager.GetString("UICurrentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalismaTakvimi.
        /// </summary>
        public static string UIExportFileName {
            get {
                return ResourceManager.GetString("UIExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Takvimi.
        /// </summary>
        public static string UIExportTitle {
            get {
                return ResourceManager.GetString("UIExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz istasyon, listede mevcut..
        /// </summary>
        public static string UIInformationSelectedStation {
            get {
                return ResourceManager.GetString("UIInformationSelectedStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakım.
        /// </summary>
        public static string UIMaintenancePreviousMenu {
            get {
                return ResourceManager.GetString("UIMaintenancePreviousMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlama &gt; Çalışma Takvimi.
        /// </summary>
        public static string UIPreviousMenu {
            get {
                return ResourceManager.GetString("UIPreviousMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz tarih daha önce eklenmiştir..
        /// </summary>
        public static string UIWarningDateMessage {
            get {
                return ResourceManager.GetString("UIWarningDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçtiğiniz satır kalıcı olarak silinecektir..
        /// </summary>
        public static string UIWarningLineDelete {
            get {
                return ResourceManager.GetString("UIWarningLineDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikkat.
        /// </summary>
        public static string UIWarningTitle {
            get {
                return ResourceManager.GetString("UIWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim Seti:.
        /// </summary>
        public static string UnitSetCodeLineLabel {
            get {
                return ResourceManager.GetString("UnitSetCodeLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen çalışma takvimi kodunu giriniz..
        /// </summary>
        public static string ValidatorCodeEmpty {
            get {
                return ResourceManager.GetString("ValidatorCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma takvimi kodu 17 karakterden fazla olamaz..
        /// </summary>
        public static string ValidatorCodeMaxLenght {
            get {
                return ResourceManager.GetString("ValidatorCodeMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen çalışma takvimi adını giriniz..
        /// </summary>
        public static string ValidatorNameEmpty {
            get {
                return ResourceManager.GetString("ValidatorNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma takvimi adı 200 karakterden fazla olamaz..
        /// </summary>
        public static string ValidatorNameMaxLenght {
            get {
                return ResourceManager.GetString("ValidatorNameMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen takvimin türünü seçiniz..
        /// </summary>
        public static string ValidatorTypeEmpty {
            get {
                return ResourceManager.GetString("ValidatorTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen takvim yılını seçiniz..
        /// </summary>
        public static string ValidatorYearEmpty {
            get {
                return ResourceManager.GetString("ValidatorYearEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Var.
        /// </summary>
        public static string WorkExist {
            get {
                return ResourceManager.GetString("WorkExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Yok.
        /// </summary>
        public static string WorkNotExist {
            get {
                return ResourceManager.GetString("WorkNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Durumu:.
        /// </summary>
        public static string WorkStateShiftStaLabel {
            get {
                return ResourceManager.GetString("WorkStateShiftStaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Durumu:.
        /// </summary>
        public static string WorkStatusLineLabel {
            get {
                return ResourceManager.GetString("WorkStatusLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YIL.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
