using TsiErp.Business.BusinessCoreServices;
using TsiErp.Entities.Entities.GeneralSystemIdentifications.MachineAndWorkforceManagementParameter.Dtos;

namespace TsiErp.Business.Entities.GeneralSystemIdentifications.MachineAndWorkforceManagementParameter.Services
{
    public interface IMachineAndWorkforceManagementParametersAppService : ICrudAppService<SelectMachineAndWorkforceManagementParametersDto, ListMachineAndWorkforceManagementParametersDto, CreateMachineAndWorkforceManagementParametersDto, UpdateMachineAndWorkforceManagementParametersDto, ListMachineAndWorkforceManagementParametersParameterDto>
    {
    }
}