//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsiErp.Localizations.Resources.NavbarMenus.Page {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NavbarMenusResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NavbarMenusResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsiErp.Localizations.Resources.NavbarMenus.Page.NavbarMenusResource", typeof(NavbarMenusResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Reçeteleri.
        /// </summary>
        public static string BOMChildMenu {
            get {
                return ResourceManager.GetString("BOMChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şube Tanımlamaları.
        /// </summary>
        public static string BranchesChildMenu {
            get {
                return ResourceManager.GetString("BranchesChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personellere Göre İş İstasyonu Verimlilik Analizi.
        /// </summary>
        public static string ByEmpStationProductivityChildMenu {
            get {
                return ResourceManager.GetString("ByEmpStationProductivityChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duruş Kodlarına Göre Personel Verimlilik Analizi.
        /// </summary>
        public static string ByHaltEmpProductivityChildMenu {
            get {
                return ResourceManager.GetString("ByHaltEmpProductivityChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duruş Kodlarına Göre İş İstasyonu Analizi.
        /// </summary>
        public static string ByHaltStationChildMenu {
            get {
                return ResourceManager.GetString("ByHaltStationChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Gruplarına Göre İş İstasyonu Performans Analizi.
        /// </summary>
        public static string ByHaltStationPerfChildMenu {
            get {
                return ResourceManager.GetString("ByHaltStationPerfChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Grubuna Göre Performans Analizi.
        /// </summary>
        public static string ByProdGrpPerfAnalysisChildMenu {
            get {
                return ResourceManager.GetString("ByProdGrpPerfAnalysisChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Grubuna Göre Hurda Analizi.
        /// </summary>
        public static string ByProdGrpScrapAnalysisChildMenu {
            get {
                return ResourceManager.GetString("ByProdGrpScrapAnalysisChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Takvimi.
        /// </summary>
        public static string CalendarMenu {
            get {
                return ResourceManager.GetString("CalendarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalibrasyon Takip Kayıtları.
        /// </summary>
        public static string CalRecordsChildMenu {
            get {
                return ResourceManager.GetString("CalRecordsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalibrasyon Doğrulama Kayıtları.
        /// </summary>
        public static string CalVerificationsChildMenu {
            get {
                return ResourceManager.GetString("CalVerificationsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fason İmalat Takip Kayıtları.
        /// </summary>
        public static string ContractProdTrackingsChildMenu {
            get {
                return ResourceManager.GetString("ContractProdTrackingsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol Şartı Başlıkları.
        /// </summary>
        public static string ControlConditionsChildMenu {
            get {
                return ResourceManager.GetString("ControlConditionsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol Türü Başlıkları.
        /// </summary>
        public static string ControlTypesChildMenu {
            get {
                return ResourceManager.GetString("ControlTypesChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fason Tedarikçi Uygunsuzluk Kayıtları Analizi.
        /// </summary>
        public static string ContUnsAnlChildMenu {
            get {
                return ResourceManager.GetString("ContUnsAnlChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fason Uygunsuzluk Kayıtları.
        /// </summary>
        public static string ContUnsRecordsChildMenu {
            get {
                return ResourceManager.GetString("ContUnsRecordsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maliyetlendirme.
        /// </summary>
        public static string CostMenu {
            get {
                return ResourceManager.GetString("CostMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Maliyet Kayıtları (CPR).
        /// </summary>
        public static string CPRChildMenu {
            get {
                return ResourceManager.GetString("CPRChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Birimi Tanımlamaları.
        /// </summary>
        public static string CurrenciesChildMenu {
            get {
                return ResourceManager.GetString("CurrenciesChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari Hesap Kartları.
        /// </summary>
        public static string CurrentAccountsChildMenu {
            get {
                return ResourceManager.GetString("CurrentAccountsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Şikayet Kayıtları.
        /// </summary>
        public static string CustCompRecordsChildMenu {
            get {
                return ResourceManager.GetString("CustCompRecordsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Departmanları.
        /// </summary>
        public static string DepartmentsChildMenu {
            get {
                return ResourceManager.GetString("DepartmentsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Listesi.
        /// </summary>
        public static string EmployeeListChildMenu {
            get {
                return ResourceManager.GetString("EmployeeListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Verimlilik Analizi.
        /// </summary>
        public static string EmployeeProductivityChildMenu {
            get {
                return ResourceManager.GetString("EmployeeProductivityChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Kayıtları.
        /// </summary>
        public static string EmployeesChildMenu {
            get {
                return ResourceManager.GetString("EmployeesChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Puanlama Kayıtları.
        /// </summary>
        public static string EmployeeScoreChildMenu {
            get {
                return ResourceManager.GetString("EmployeeScoreChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel Puanlama Listesi.
        /// </summary>
        public static string EmployeeScoreListChildMenu {
            get {
                return ResourceManager.GetString("EmployeeScoreListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekipman Yönetimi.
        /// </summary>
        public static string EquipmentManagementMenu {
            get {
                return ResourceManager.GetString("EquipmentManagementMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekipman İşlemleri.
        /// </summary>
        public static string EquipmentOperationsMenu {
            get {
                return ResourceManager.GetString("EquipmentOperationsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekipman Kayıtları.
        /// </summary>
        public static string EquipmentRecordsChildMenu {
            get {
                return ResourceManager.GetString("EquipmentRecordsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Kuru Tablosu.
        /// </summary>
        public static string ExRatesChildMenu {
            get {
                return ResourceManager.GetString("ExRatesChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Kontrol Kayıtları.
        /// </summary>
        public static string FinalControlRecordsChildMenu {
            get {
                return ResourceManager.GetString("FinalControlRecordsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Kontrol Uygunsuzluk Kayıtları.
        /// </summary>
        public static string FinalControlUnsRecordsChildMenu {
            get {
                return ResourceManager.GetString("FinalControlUnsRecordsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finans Yönetimi .
        /// </summary>
        public static string FinanceManagementParametersChildMenu {
            get {
                return ResourceManager.GetString("FinanceManagementParametersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finans Yönetimi.
        /// </summary>
        public static string FinanceManagementParentMenu {
            get {
                return ResourceManager.GetString("FinanceManagementParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Forecast Kayıtları.
        /// </summary>
        public static string ForecastsChildMenu {
            get {
                return ResourceManager.GetString("ForecastsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Fabrika OEE Analizi.
        /// </summary>
        public static string GeneralOEEChildMenu {
            get {
                return ResourceManager.GetString("GeneralOEEChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Parametreler.
        /// </summary>
        public static string GeneralParametersChildMenu {
            get {
                return ResourceManager.GetString("GeneralParametersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Sistem Tanımlamaları.
        /// </summary>
        public static string GeneralSystemIdentificationsParentMenu {
            get {
                return ResourceManager.GetString("GeneralSystemIdentificationsParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Sistem Parametreleri.
        /// </summary>
        public static string GeneralSystemParametersParentMenu {
            get {
                return ResourceManager.GetString("GeneralSystemParametersParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duruş Kodları.
        /// </summary>
        public static string HaltReasonsChildMenu {
            get {
                return ResourceManager.GetString("HaltReasonsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envanter Listesi.
        /// </summary>
        public static string InventoryListChildMenu {
            get {
                return ResourceManager.GetString("InventoryListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IoT.
        /// </summary>
        public static string IoTProdTrackingsChildMenu {
            get {
                return ResourceManager.GetString("IoTProdTrackingsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malzeme Listesi.
        /// </summary>
        public static string ListofMaterialsChildMenu {
            get {
                return ResourceManager.GetString("ListofMaterialsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine &amp; İş Gücü Yönetimi .
        /// </summary>
        public static string MachineAndWorkforceManagementParametersChildMenu {
            get {
                return ResourceManager.GetString("MachineAndWorkforceManagementParametersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makine &amp; İş Gücü Yönetimi.
        /// </summary>
        public static string MachWorkForceManagementParentMenu {
            get {
                return ResourceManager.GetString("MachWorkForceManagementParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakım Talimatları.
        /// </summary>
        public static string MainInstructionsChildMenu {
            get {
                return ResourceManager.GetString("MainInstructionsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakım Malzemesi Satınalma Süreç Takibi.
        /// </summary>
        public static string MainMatPurchaseTrackingChildMenu {
            get {
                return ResourceManager.GetString("MainMatPurchaseTrackingChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakım Malzemesi İhtiyaç Planlaması.
        /// </summary>
        public static string MainMatReqPlanningChildMenu {
            get {
                return ResourceManager.GetString("MainMatReqPlanningChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakım Periyotları.
        /// </summary>
        public static string MainPeriodsChildMenu {
            get {
                return ResourceManager.GetString("MainPeriodsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Kayıtlar.
        /// </summary>
        public static string MainRecordsMenu {
            get {
                return ResourceManager.GetString("MainRecordsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakım Yönetimi .
        /// </summary>
        public static string MaintenanceManagementParametersChildMenu {
            get {
                return ResourceManager.GetString("MaintenanceManagementParametersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakım Yönetimi.
        /// </summary>
        public static string MaintenanceManagementParentMenu {
            get {
                return ResourceManager.GetString("MaintenanceManagementParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malzeme/Depo Durum Raporu.
        /// </summary>
        public static string MaterialWarehouseStatusChildMenu {
            get {
                return ResourceManager.GetString("MaterialWarehouseStatusChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara Kontrol Başlıkları.
        /// </summary>
        public static string MidControlChildMenu {
            get {
                return ResourceManager.GetString("MidControlChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara Kontrol Kayıtları.
        /// </summary>
        public static string MidControlRecordsChildMenu {
            get {
                return ResourceManager.GetString("MidControlRecordsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malzeme İhtiyaç Planlaması (MRP).
        /// </summary>
        public static string MRPChildMenu {
            get {
                return ResourceManager.GetString("MRPChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Kaynak Planlaması (MRPII).
        /// </summary>
        public static string MRPIIChildMenu {
            get {
                return ResourceManager.GetString("MRPIIChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasyonlar.
        /// </summary>
        public static string OperationsMenu {
            get {
                return ResourceManager.GetString("OperationsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasyon Uygunsuzluk Kayıtları.
        /// </summary>
        public static string OprUnsRecordsChildMenu {
            get {
                return ResourceManager.GetString("OprUnsRecordsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paket Fişleri.
        /// </summary>
        public static string PackageFichesChildMenu {
            get {
                return ResourceManager.GetString("PackageFichesChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paket Fişleri Listesi.
        /// </summary>
        public static string PackageFichesListChildMenu {
            get {
                return ResourceManager.GetString("PackageFichesListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeki Listesi.
        /// </summary>
        public static string PackingListChildMenu {
            get {
                return ResourceManager.GetString("PackingListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çeki Listeleri.
        /// </summary>
        public static string PackingListsChildMenu {
            get {
                return ResourceManager.GetString("PackingListsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palet Kayıtları.
        /// </summary>
        public static string PalletRecordsChildMenu {
            get {
                return ResourceManager.GetString("PalletRecordsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palet Kayıtları Listesi.
        /// </summary>
        public static string PalletRecordsListChildMenu {
            get {
                return ResourceManager.GetString("PalletRecordsListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Planları.
        /// </summary>
        public static string PaymentPlansChildMenu {
            get {
                return ResourceManager.GetString("PaymentPlansChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dönem Kayıtları.
        /// </summary>
        public static string PeriodsChildMenu {
            get {
                return ResourceManager.GetString("PeriodsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önleyici/Planlı Bakım Kayıtları.
        /// </summary>
        public static string PlannedMainChildMenu {
            get {
                return ResourceManager.GetString("PlannedMainChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlama Yönetimi .
        /// </summary>
        public static string PlanningManagementParametersChildMenu {
            get {
                return ResourceManager.GetString("PlanningManagementParametersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlama.
        /// </summary>
        public static string PlanningParentMenu {
            get {
                return ResourceManager.GetString("PlanningParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Operasyon Kayıtları.
        /// </summary>
        public static string ProdOperationsChildMenu {
            get {
                return ResourceManager.GetString("ProdOperationsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Emri Uygunsuzluk Kayıtları.
        /// </summary>
        public static string ProdOrderRecordsChildMenu {
            get {
                return ResourceManager.GetString("ProdOrderRecordsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Emri Uygunsuzluk Kayıtları Analizi.
        /// </summary>
        public static string ProdOrderUnsAnlChildMenu {
            get {
                return ResourceManager.GetString("ProdOrderUnsAnlChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Takip Kayıtları Listesi.
        /// </summary>
        public static string ProdTrackingListChildMenu {
            get {
                return ResourceManager.GetString("ProdTrackingListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuel.
        /// </summary>
        public static string ProdTrackingsChildMenu {
            get {
                return ResourceManager.GetString("ProdTrackingsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Grupları.
        /// </summary>
        public static string ProductGroupsChildMenu {
            get {
                return ResourceManager.GetString("ProductGroupsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Yönetimi .
        /// </summary>
        public static string ProductionManagementParametersChildMenu {
            get {
                return ResourceManager.GetString("ProductionManagementParametersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Yönetimi.
        /// </summary>
        public static string ProductionManagementParentMenu {
            get {
                return ResourceManager.GetString("ProductionManagementParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Emirleri Listesi.
        /// </summary>
        public static string ProductionOrderListChildMenu {
            get {
                return ResourceManager.GetString("ProductionOrderListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Emirleri.
        /// </summary>
        public static string ProductionOrdersChildMenu {
            get {
                return ResourceManager.GetString("ProductionOrdersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Planlama.
        /// </summary>
        public static string ProductionPlanningMenu {
            get {
                return ResourceManager.GetString("ProductionPlanningMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Takip Kayıtları.
        /// </summary>
        public static string ProductionTrackingRecordsMenu {
            get {
                return ResourceManager.GetString("ProductionTrackingRecordsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Referans Numaraları.
        /// </summary>
        public static string ProductRefNumbersChildMenu {
            get {
                return ResourceManager.GetString("ProductRefNumbersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Kartları.
        /// </summary>
        public static string ProductsChildMenu {
            get {
                return ResourceManager.GetString("ProductsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Yönetimi .
        /// </summary>
        public static string PurchaseManagementParametersChildMenu {
            get {
                return ResourceManager.GetString("PurchaseManagementParametersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Yönetimi.
        /// </summary>
        public static string PurchaseManagementParentMenu {
            get {
                return ResourceManager.GetString("PurchaseManagementParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Siparişleri Listesi.
        /// </summary>
        public static string PurchaseOrderFicheListChildMenu {
            get {
                return ResourceManager.GetString("PurchaseOrderFicheListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Siparişleri.
        /// </summary>
        public static string PurchaseOrdersChildMenu {
            get {
                return ResourceManager.GetString("PurchaseOrdersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Fiyat Listeleri.
        /// </summary>
        public static string PurchasePricesChildMenu {
            get {
                return ResourceManager.GetString("PurchasePricesChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Talep Fişi Listesi.
        /// </summary>
        public static string PurchaseRequestFicheListChildMenu {
            get {
                return ResourceManager.GetString("PurchaseRequestFicheListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Talep Fişleri.
        /// </summary>
        public static string PurchaseRequestsChildMenu {
            get {
                return ResourceManager.GetString("PurchaseRequestsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satın Alma Uygunsuzluk Kayıtları.
        /// </summary>
        public static string PurchUnsRecordsChildMenu {
            get {
                return ResourceManager.GetString("PurchUnsRecordsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satınalma Uygunuzluk Kayıtları Analizi.
        /// </summary>
        public static string PurcUnsAnlChildMenu {
            get {
                return ResourceManager.GetString("PurcUnsAnlChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalite Kontrol .
        /// </summary>
        public static string QualityControlParametersChildMenu {
            get {
                return ResourceManager.GetString("QualityControlParametersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalite Kontrol.
        /// </summary>
        public static string QualityControlParentMenu {
            get {
                return ResourceManager.GetString("QualityControlParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlar.
        /// </summary>
        public static string ReportsMenu {
            get {
                return ResourceManager.GetString("ReportsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Tanımlamaları.
        /// </summary>
        public static string RoleDefinitionsChildMenu {
            get {
                return ResourceManager.GetString("RoleDefinitionsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üretim Rotaları.
        /// </summary>
        public static string RoutesChildMenu {
            get {
                return ResourceManager.GetString("RoutesChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Yönetimi .
        /// </summary>
        public static string SalesManagementParametersChildMenu {
            get {
                return ResourceManager.GetString("SalesManagementParametersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Yönetimi.
        /// </summary>
        public static string SalesManagementParentMenu {
            get {
                return ResourceManager.GetString("SalesManagementParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Siparişleri Listesi.
        /// </summary>
        public static string SalesOrderFicheListChildMenu {
            get {
                return ResourceManager.GetString("SalesOrderFicheListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Siparişleri.
        /// </summary>
        public static string SalesOrdersChildMenu {
            get {
                return ResourceManager.GetString("SalesOrdersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Fiyat Listeleri.
        /// </summary>
        public static string SalesPricesChildMenu {
            get {
                return ResourceManager.GetString("SalesPricesChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verilen Teklif Listesi.
        /// </summary>
        public static string SalesPropositionFicheListChildMenu {
            get {
                return ResourceManager.GetString("SalesPropositionFicheListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verilen Teklifler.
        /// </summary>
        public static string SalesPropositionsChildMenu {
            get {
                return ResourceManager.GetString("SalesPropositionsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vardiya Tanımlamaları.
        /// </summary>
        public static string ShiftsChildMenu {
            get {
                return ResourceManager.GetString("ShiftsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sevkiyat Yönetimi.
        /// </summary>
        public static string ShipmentParentMenu {
            get {
                return ResourceManager.GetString("ShipmentParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sevkiyat Planlama.
        /// </summary>
        public static string ShipmentPlanningChildMenu {
            get {
                return ResourceManager.GetString("ShipmentPlanningChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sevkiyat Adresleri.
        /// </summary>
        public static string ShippingAdressesChildMenu {
            get {
                return ResourceManager.GetString("ShippingAdressesChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sevkiyat Yönetimi .
        /// </summary>
        public static string ShippingManagementParametersChildMenu {
            get {
                return ResourceManager.GetString("ShippingManagementParametersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPC &amp; FMEA.
        /// </summary>
        public static string SPCFMEAChildMenu {
            get {
                return ResourceManager.GetString("SPCFMEAChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş İstasyonu Maliyet Kayıtları.
        /// </summary>
        public static string StationCostChildMenu {
            get {
                return ResourceManager.GetString("StationCostChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş İstasyon Maliyetleri Listesi.
        /// </summary>
        public static string StationCostListChildMenu {
            get {
                return ResourceManager.GetString("StationCostListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Merkezleri.
        /// </summary>
        public static string StationGroupChildMenu {
            get {
                return ResourceManager.GetString("StationGroupChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş İstasyonları Listesi.
        /// </summary>
        public static string StationListChildMenu {
            get {
                return ResourceManager.GetString("StationListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş İstasyonları OEE Analizi.
        /// </summary>
        public static string StationOEEChildMenu {
            get {
                return ResourceManager.GetString("StationOEEChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş İstasyonları.
        /// </summary>
        public static string StationsChildMenu {
            get {
                return ResourceManager.GetString("StationsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Fişleri.
        /// </summary>
        public static string StockFichesChildMenu {
            get {
                return ResourceManager.GetString("StockFichesChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Yönetimi .
        /// </summary>
        public static string StockManagementParametersChildMenu {
            get {
                return ResourceManager.GetString("StockManagementParametersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Yönetimi.
        /// </summary>
        public static string StockManagementParentMenu {
            get {
                return ResourceManager.GetString("StockManagementParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknik Analizler.
        /// </summary>
        public static string TechAnlChildMenu {
            get {
                return ResourceManager.GetString("TechAnlChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknik Resimler.
        /// </summary>
        public static string TechnicalDrawingsChildMenu {
            get {
                return ResourceManager.GetString("TechnicalDrawingsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şablon Operasyon Kayıtları.
        /// </summary>
        public static string TempOperationsChildMenu {
            get {
                return ResourceManager.GetString("TempOperationsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hareketler.
        /// </summary>
        public static string TransactionsMenu {
            get {
                return ResourceManager.GetString("TransactionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birim Setleri.
        /// </summary>
        public static string UnitSetsChildMenu {
            get {
                return ResourceManager.GetString("UnitSetsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arıza/Plansız Bakım Kayıtları.
        /// </summary>
        public static string UnplannedMainChildMenu {
            get {
                return ResourceManager.GetString("UnplannedMainChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygunsuzluk Başlıkları.
        /// </summary>
        public static string UnsItemsChildMenu {
            get {
                return ResourceManager.GetString("UnsItemsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygunsuzluk Kayıtları.
        /// </summary>
        public static string UnsRecordsMenu {
            get {
                return ResourceManager.GetString("UnsRecordsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygunsuzluk Türü Başlıkları.
        /// </summary>
        public static string UnsTypesItemsChildMenu {
            get {
                return ResourceManager.GetString("UnsTypesItemsChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Grupları.
        /// </summary>
        public static string UserGrpChildMenu {
            get {
                return ResourceManager.GetString("UserGrpChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Tanımlamaları.
        /// </summary>
        public static string UsersChildMenu {
            get {
                return ResourceManager.GetString("UsersChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depo Kartları.
        /// </summary>
        public static string WarehousesChildMenu {
            get {
                return ResourceManager.GetString("WarehousesChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Emirleri Listesi.
        /// </summary>
        public static string WorkOrderListChildMenu {
            get {
                return ResourceManager.GetString("WorkOrderListChildMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Emirleri.
        /// </summary>
        public static string WorkOrdersChildMenu {
            get {
                return ResourceManager.GetString("WorkOrdersChildMenu", resourceCulture);
            }
        }
    }
}
