//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsiErp.Localizations.Resources.ProductionOrderChangeReports.Page {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductionOrderChangeReportsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductionOrderChangeReportsResource() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TsiErp.Localizations.Resources.ProductionOrderChangeReports.Page.ProductionOrderC" +
                            "hangeReportsResource", typeof(ProductionOrderChangeReportsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Aksiyon: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ActionLabel {
            get {
                return ResourceManager.GetString("ActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kapat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aynı kodlu bir kayıt bulunmaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CodeControlManager {
            get {
                return ResourceManager.GetString("CodeControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üretim İptal Edildi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ComboboxProductionCancel {
            get {
                return ResourceManager.GetString("ComboboxProductionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeniden İmalat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ComboboxRemanufacturing {
            get {
                return ResourceManager.GetString("ComboboxRemanufacturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hurda benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ComboboxScrap {
            get {
                return ResourceManager.GetString("ComboboxScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TARİH benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Date_ {
            get {
                return ResourceManager.GetString("Date_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tarih: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Date_Label {
            get {
                return ResourceManager.GetString("Date_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silmek istediğinize emin misiniz ? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeleteConfirmationDescriptionBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeleteConfirmationTitleBase {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hareket gören kayıtlar silinemez. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeleteControlManager {
            get {
                return ResourceManager.GetString("DeleteControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt başarıyla silindi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Açıklama: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Description_Label {
            get {
                return ResourceManager.GetString("Description_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üretim Emri Değişiklik Kayıtları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EditModalTitle {
            get {
                return ResourceManager.GetString("EditModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hata benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FİŞ NO.
        ///   UretimEmriDegisiklikKayitlari benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExportFileName {
            get {
                return ResourceManager.GetString("ExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üretim Emri Değişiklik Kayıtları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ExportTitle {
            get {
                return ResourceManager.GetString("ExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FİŞ NO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FicheNo {
            get {
                return ResourceManager.GetString("FicheNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fiş Numarası: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FicheNoLabel {
            get {
                return ResourceManager.GetString("FicheNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen Bekleyin.. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoadingCaption {
            get {
                return ResourceManager.GetString("LoadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıtlar Yükleniyor.. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seçtiğiniz kayıt {0} tarafından kullanılmaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessagePopupInformationDescriptionBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationDescriptionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilgi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MessagePopupInformationTitleBase {
            get {
                return ResourceManager.GetString("MessagePopupInformationTitleBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOK KODU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stok Kodu: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductCodeLabel {
            get {
                return ResourceManager.GetString("ProductCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductionOrderChangeReportsContextAdd {
            get {
                return ResourceManager.GetString("ProductionOrderChangeReportsContextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Değiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductionOrderChangeReportsContextChange {
            get {
                return ResourceManager.GetString("ProductionOrderChangeReportsContextChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductionOrderChangeReportsContextDelete {
            get {
                return ResourceManager.GetString("ProductionOrderChangeReportsContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncelle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductionOrderChangeReportsContextRefresh {
            get {
                return ResourceManager.GetString("ProductionOrderChangeReportsContextRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜRETİM EMRİ FİŞ NO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductionOrderFicheNo {
            get {
                return ResourceManager.GetString("ProductionOrderFicheNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üretim Emri Fiş No: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductionOrderFicheNoLabel {
            get {
                return ResourceManager.GetString("ProductionOrderFicheNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÜRETİM EMRİ FİŞ NO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductionOrderModalGridFicheNo {
            get {
                return ResourceManager.GetString("ProductionOrderModalGridFicheNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOK KODU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductionOrderModalGridFinishedProductCode {
            get {
                return ResourceManager.GetString("ProductionOrderModalGridFinishedProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOK AÇIKLAMASI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductionOrderModalGridFinishedProductName {
            get {
                return ResourceManager.GetString("ProductionOrderModalGridFinishedProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SİPARİŞ NO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductionOrderModalGridOrderFicheNo {
            get {
                return ResourceManager.GetString("ProductionOrderModalGridOrderFicheNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üretim Emirleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductionOrderModalTitle {
            get {
                return ResourceManager.GetString("ProductionOrderModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOK AÇIKLAMASI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stok Açıklaması: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ProductNameLabel {
            get {
                return ResourceManager.GetString("ProductNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SİPARİŞ NO benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SalesOrderFicheNo {
            get {
                return ResourceManager.GetString("SalesOrderFicheNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sipariş No: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SalesOrderFicheNoLabel {
            get {
                return ResourceManager.GetString("SalesOrderFicheNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kaydet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üretim Emri Değişiklik Kayıtları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UICurrentMenu {
            get {
                return ResourceManager.GetString("UICurrentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalite Kontrol &gt; Hareketler &gt; Uygunsuzluk Kayıtları.
        /// </summary>
        public static string UIPreviousMenu {
            get {
                return ResourceManager.GetString("UIPreviousMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UYGUNSUZLUK BAŞLIĞI KODU benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnsuitabilityItemModalGridCode {
            get {
                return ResourceManager.GetString("UnsuitabilityItemModalGridCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UYGUNSUZLUK BAŞLIĞI ADI benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnsuitabilityItemModalGridName {
            get {
                return ResourceManager.GetString("UnsuitabilityItemModalGridName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uygunsuzluk Başlıkları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnsuitabilityItemModalTitle {
            get {
                return ResourceManager.GetString("UnsuitabilityItemModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hata Başlığı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UnsuitabilityItemsNameLabel {
            get {
                return ResourceManager.GetString("UnsuitabilityItemsNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aynı kodlu bir kayıt bulunmaktadır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string UpdateControlManager {
            get {
                return ResourceManager.GetString("UpdateControlManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen üretim emri değişiklik fiş numarasını yazın. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ValidatorCodeEmpty {
            get {
                return ResourceManager.GetString("ValidatorCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üretim emri değişiklik fiş numarası 17 karakterden fazla olamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ValidatorCodeMaxLenght {
            get {
                return ResourceManager.GetString("ValidatorCodeMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen stok seçiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ValidatorProductID {
            get {
                return ResourceManager.GetString("ValidatorProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen üretim emri seçiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ValidatorProductionOrderID {
            get {
                return ResourceManager.GetString("ValidatorProductionOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen satış siparişi seçiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ValidatorSalesOrderID {
            get {
                return ResourceManager.GetString("ValidatorSalesOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen hata kodu seçiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ValidatorUnsuitabilityItemsID {
            get {
                return ResourceManager.GetString("ValidatorUnsuitabilityItemsID", resourceCulture);
            }
        }
    }
}
